"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const ROOT=path.resolve(__dirname,"..");
function api(){const c={Object,Array,Math};c.window=c;c.globalThis=c;vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(ROOT,"js/pocket-starling-sequence-shadow.js"),"utf8"),c);return c.PocketStarlingSequenceShadow;}
function plain(value){return JSON.parse(JSON.stringify(value));}
function valid(page,cap){assert.ok(page.kind==="leaf"||page.kind==="branch");if(page.kind==="leaf")assert.ok(page.items.length<=cap);else{assert.ok(page.children.length<=cap);assert.equal(page.count,page.children.reduce((n,c)=>n+c.count,0));page.children.forEach(c=>valid(c,cap));}}
test("P107a1 builds a bounded multi-level immutable sequence",()=>{const a=api(),items=Array.from({length:1024},(_,i)=>"n"+i),built=a.build(items,{capacity:4});assert.equal(built.ok,true);assert.deepEqual(plain(a.materialise(built.root)),items);assert.ok(a.height(built.root)>2);valid(built.root,4);});
test("P107a1 same-gap insert path-copies while retaining distant leaf and branch references",()=>{const a=api(),items=Array.from({length:256},(_,i)=>"n"+i),base=a.build(items,{capacity:4}).root,distant=a.pages(base).at(-1);let root=base,expected=items.slice();for(let i=0;i<40;i++){const next=a.insertAt(root,2,"x"+i,{capacity:4});assert.equal(next.ok,true);root=next.root;expected.splice(2,0,"x"+i);valid(root,4);}assert.deepEqual(plain(a.materialise(root)),expected);assert.ok(a.pages(root).includes(distant));assert.deepEqual(plain(a.materialise(base)),items);});
test("P107a1 remove path-copies and collapses empty local roots",()=>{const a=api(),items=Array.from({length:64},(_,i)=>"n"+i),base=a.build(items,{capacity:4}).root,distant=a.pages(base).at(-1),next=a.removeAt(base,1,{capacity:4});assert.deepEqual(plain(a.materialise(next.root)),items.filter((_,i)=>i!==1));assert.ok(a.pages(next.root).includes(distant));assert.deepEqual(plain(a.materialise(base)),items);let single=a.build(["a"],{capacity:4}).root;single=a.removeAt(single,0,{capacity:4}).root;assert.deepEqual(plain(a.materialise(single)),[]);});
