"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const ROOT=path.resolve(__dirname,".."), CODECS=["js/pocket-state.js","js/pocket-data.js","js/pocket-outline-persistence-policy.js","js/pocket-editor-metadata.js","js/pocket-pe-import-preserve.js","js/pocket-storage.js","js/pocket-import.js"];
const source=(f)=>fs.readFileSync(path.join(ROOT,f),"utf8"),plain=(v)=>JSON.parse(JSON.stringify(v));
function ctx(){const c={URL,Date,Math,JSON,Map,Set,Object,Array,String,Number,Boolean,Promise,console:{log(){},info(){},warn(){},error(){}},localStorage:{getItem(){return null},setItem(){},removeItem(){}},document:{body:{classList:{add(){},remove(){},toggle(){}}},getElementById(){return null},addEventListener(){}},navigator:{clipboard:{}},location:{href:"https://example.test"},indexedDB:null,open(){},close(){},setTimeout(){return 1},clearTimeout(){},requestAnimationFrame(){return 1},cancelAnimationFrame(){}};c.window=c;c.globalThis=c;vm.createContext(c);[...CODECS,"js/pocket-starling-shadow.js","js/pocket-starling-sequence-shadow.js","js/pocket-starling-placement-shadow.js","js/pocket-starling-bridge-shadow.js"].forEach(f=>vm.runInContext(source(f),c,{filename:f}));return c}
function norm(c){c.raw={schema:"portal.mtt.web.v1",writtenAt:"2026-08-28T00:00:00.000Z",rootExtra:{kept:true},data:{extra:{kept:true},mainThoughtTreeTombstones:[{id:"gone"}],mainThoughtTree:[{id:"a",parentId:"root",label:"Zulu",order:10000,editor:{opaque:true}},{id:"b",parentId:"root",label:"Alpha",order:5000},{id:"c",parentId:"root",label:"Beta",order:5000},{id:"done",parentId:"root",label:"Completed",order:1000,system:{kind:"bucket",bucketType:"completed",managed:true,pinnedLast:true}},{id:"child",parentId:"a",label:"Child",order:1000}]}};return vm.runInContext("normaliseInput(raw)",c)}
function canon(c,n,t){c.n=n;c.t=t;return vm.runInContext("buildCanonicalPocketPayload(n,{writtenAt:t})",c)}
test("P107a3 projects current comparator order and round-trips canonical P106 material exactly",()=>{const c=ctx(),n=norm(c),a=c.PocketStarlingBridgeShadow,b=a.encode(n,{capacity:4});assert.equal(b.ok,true);assert.deepEqual(plain(a.audit(b.bridge)),{ok:true});assert.deepEqual(plain(a.decodeExact(b.bridge).norm),plain(n));assert.deepEqual(plain(canon(c,n,"2026-08-28T12:00:00.000Z")),plain(canon(c,a.decodeExact(b.bridge).norm,"2026-08-28T12:00:00.000Z")));const order=plain(c.PocketStarlingPlacementShadow.audit(b.bridge.structural).relation.children.root);assert.deepEqual(order,["b","c","a","done"]);assert.deepEqual(Object.keys(c.PocketStarlingPlacementShadow.getPlacement(b.bridge.structural,"b")).sort(),["nodeId","parentId"]);assert.equal(source("index.html").includes("pocket-starling-bridge-shadow.js"),false)});
test("P107a3 fails closed for parent, membership and order divergence without mutating structure",()=>{const c=ctx(),n=norm(c),a=c.PocketStarlingBridgeShadow,p=c.PocketStarlingPlacementShadow,b=a.encode(n).bridge,original=plain(p.audit(b.structural).relation);function altered(r){return Object.freeze({...b,structural:p.build(r,{capacity:4}).model})}const parent=plain(p.audit(b.structural).relation);parent.parents.child="root";parent.children.a=[];parent.children.root.push("child");assert.equal(a.audit(altered(parent)).reason,"bridge-parent-mismatch");const order=plain(p.audit(b.structural).relation);[order.children.root[0],order.children.root[1]]=[order.children.root[1],order.children.root[0]];assert.equal(a.audit(altered(order)).reason,"bridge-order-mismatch");const membership=plain(p.audit(b.structural).relation);membership.nodeIds.push("extra");membership.parents.extra="root";membership.children.root.push("extra");assert.equal(a.audit(altered(membership)).reason,"bridge-membership-mismatch");assert.deepEqual(plain(p.audit(b.structural).relation),original);assert.equal(a.decodeExact(altered(order)).ok,false)});
test("P107a3 legacy order changes do not mutate the structural projection",()=>{const c=ctx(),n=norm(c),a=c.PocketStarlingBridgeShadow,p=c.PocketStarlingPlacementShadow,b=a.encode(n).bridge,root=p.getChildrenRoot(b.structural,"root"),variant=plain(b.compatibility);variant.placements.find(x=>x.nodeId==="a").order=1;const changed=Object.freeze({...b,compatibility:variant});assert.equal(a.audit(changed).reason,"bridge-order-mismatch");assert.strictEqual(p.getChildrenRoot(changed.structural,"root"),root)});
