"use strict";
const test=require("node:test"), assert=require("node:assert/strict"), fs=require("node:fs"), path=require("node:path"), vm=require("node:vm"), {webcrypto}=require("node:crypto"), {createProductionReleaseManifest}=require("../sync-service/pocket-sync-production-server.js"), ROOT=path.resolve(__dirname,"..");
const SCRIPTS=["js/pocket-state.js","js/pocket-data.js","js/pocket-outline-persistence-policy.js","js/pocket-editor-metadata.js","js/pocket-pe-import-preserve.js","js/pocket-storage.js","js/pocket-import.js","js/pocket-starling-shadow.js","js/pocket-starling-sequence-shadow.js","js/pocket-starling-placement-shadow.js","js/pocket-starling-bridge-shadow.js","js/pocket-starling-root-shadow.js","js/pocket-starling-object-seal-shadow.js","js/pocket-sync-crypto.js","js/pocket-starling-crypto-shadow.js","js/pocket-starling-storage-shadow.js","js/pocket-starling-head-shadow.js","js/pocket-sync-remote-client.js","js/pocket-starling-logical-edit-shadow.js","js/pocket-starling-publication-shadow.js","js/pocket-starling-remote-open-shadow.js"];
function runtime(){const c={crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,URL,Date,Math,JSON,Map,Set,WeakMap,WeakSet,Object,Array,String,Number,Boolean,Promise,Error,btoa:v=>Buffer.from(v,"binary").toString("base64"),atob:v=>Buffer.from(v,"base64").toString("binary"),localStorage:{getItem(){},setItem(){},removeItem(){}},document:{body:{classList:{add(){},remove(){},toggle(){}}},getElementById(){},addEventListener(){}},navigator:{clipboard:{}},location:{href:"https://example.test"},indexedDB:null,open(){},close(){},setTimeout(){return 1},clearTimeout(){},requestAnimationFrame(){return 1},cancelAnimationFrame(){}};c.window=c;c.globalThis=c;vm.createContext(c);for(const f of SCRIPTS)vm.runInContext(fs.readFileSync(path.join(ROOT,f),"utf8"),c,{filename:f});return c}
const plain=v=>JSON.parse(JSON.stringify(v)), context=()=>({syncedPocketId:"p124"}), head=(revision,sealRef)=>({schema:"pocket.starling.head.v1",revision,sealRef});
async function fixture(c){const encoded=c.PocketStarlingBridgeShadow.encode({schema:"portal.mtt.web.v1",writtenAt:"2026-08-30T00:00:00.000Z",nodes:Array.from({length:32},(_,i)=>({id:`n${i}`,parentId:"root",order:i,label:`Node ${i}`,value:i})),tombstones:[],rootExtras:{},dataExtras:{}},{capacity:4}),built=c.PocketStarlingRootShadow.build(encoded.bridge),stager=c.PocketStarlingObjectSealShadow.createStager(),logical=c.PocketStarlingObjectSealShadow.stageCandidate(stager,built.state,{previousSealRef:null}).stage,wrapping=await c.PocketSyncCrypto.generateDeviceWrappingKey(),bundle=await c.PocketSyncCrypto.createMasterKeyBundle([{context:{syncedPocketId:"p124",envelopeId:"device",envelopeKind:"device",envelopeVersion:1},wrappingKey:wrapping}]),physical=await c.PocketStarlingStorageShadow.stageCandidate({sealRef:logical.sealRef,resolveLogical:r=>stager.store.get(r),masterKey:bundle.masterKey,context:context()}),records=new Map(physical.newRecords.map(e=>[e.storageRef,e.record]));return{built,logical,physical,records,key:bundle.masterKey}}
function opener(c,data,calls,current=head(1,data.physical.sealStorageRef),behaviour={}){const transport={async request(route,body){calls.push([route,plain(body)]);if(behaviour.request)return behaviour.request(route,body);const common={apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId};if(route==="readShadowHead")return{status:200,body:{...common,head:current}};const record=data.records.get(body.storageRef);return{status:200,body:{...common,storageRef:body.storageRef,present:!!record,record:record||null}}}},service=c.PocketSyncRemoteClient.createObjectHeadService({transport});return c.PocketStarlingRemoteOpenShadow.createRemoteOpener({objectHeadService:service,operationIdFactory:behaviour.factory||((kind,index)=>`${kind}-${index}`)})}
test("P124 opens the authoritative remote Seal lazily through real P120",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(result.outcome,"opened");assert.equal(Object.isFrozen(result),true);assert.deepEqual(Object.keys(result.session),["acceptedSealRef","resolveLogical","createReuseProof","readContent","readPlacement","diagnostics"]);assert.deepEqual(calls.slice(0,3).map(([route])=>route),["readShadowHead","getOpaqueObject","getOpaqueObject"]);assert.equal(calls[1][1].storageRef,data.physical.sealStorageRef);assert.equal((await result.session.readContent("n3")).payload.value,3);const before=calls.length;await result.session.readContent("n3");assert.equal(calls.length,before);assert.equal(Object.isFrozen(result.session.createReuseProof()),true)});
test("P124 returns empty states without GETs and keeps local input/ID failures local",async()=>{const c=runtime(),data=await fixture(c);for(const current of [null,head(0,null)]){const calls=[],result=await opener(c,data,calls,current).openRemote({masterKey:data.key,context:context()});assert.equal(result.outcome,current===null?"uninitialised":"empty");assert.equal(calls.length,1)}const calls=[];await assert.rejects(opener(c,data,calls).openRemote({masterKey:{},context:context()}));assert.equal(calls.length,0)});
test("P124a keeps failed GET claims local and preserves the first actual GET index",async()=>{const c=runtime(),data=await fixture(c),failed=[];await assert.rejects(opener(c,data,failed,undefined,{factory:(kind,index)=>kind==="get-object"?" ":`${kind}-${index}`}).openRemote({masterKey:data.key,context:context()}),e=>e&&e.code==="remote-open-operation-id-invalid");assert.deepEqual(failed.map(([route])=>route),["readShadowHead"]);const calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(result.outcome,"opened");assert.equal(calls[1][1].operationId,"get-object-0")});
test("P124 rejects invalid context before Head I/O",async()=>{const c=runtime(),data=await fixture(c),calls=[];await assert.rejects(opener(c,data,calls).openRemote({masterKey:data.key,context:{syncedPocketId:" "}}));assert.equal(calls.length,0)});
test("P124 rejects caller authority fields before Head I/O",async()=>{const c=runtime(),data=await fixture(c);for(const field of ["head","sealRef","acceptedSealStorageRef","revision","acceptedBaseComplete"]){const calls=[];await assert.rejects(opener(c,data,calls).openRemote({...{masterKey:data.key,context:context()},[field]:"forged"}));assert.equal(calls.length,0)}});
test("P124 keeps read-head ID failure local",async()=>{const c=runtime(),data=await fixture(c),calls=[];await assert.rejects(opener(c,data,calls,undefined,{factory:()=>" "}).openRemote({masterKey:data.key,context:context()}),e=>e&&e.code==="remote-open-operation-id-invalid");assert.equal(calls.length,0)});
test("P124 fails closed when the authoritative Seal is absent",async()=>{const c=runtime(),data=await fixture(c),calls=[];await assert.rejects(opener(c,data,calls,undefined,{request:(route,body)=>route==="readShadowHead"?{status:200,body:{apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId,head:head(1,data.physical.sealStorageRef)}}:{status:200,body:{apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId,storageRef:body.storageRef,present:false,record:null}}}).openRemote({masterKey:data.key,context:context()}),e=>e&&e.code==="remote-open-object-missing");assert.deepEqual(calls.map(x=>x[0]),["readShadowHead","getOpaqueObject"])});
test("P124 propagates Head transport failure without GET retry",async()=>{const c=runtime(),data=await fixture(c),calls=[];await assert.rejects(opener(c,data,calls,undefined,{request:()=>{throw new Error("offline")}}).openRemote({masterKey:data.key,context:context()}),e=>e&&e.code==="remote-unavailable");assert.deepEqual(calls.map(x=>x[0]),["readShadowHead"])});
test("P124 result Head is frozen authoritative physical authority",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(Object.isFrozen(result.head),true);assert.equal(result.head.sealRef,data.physical.sealStorageRef);assert.notEqual(result.session.acceptedSealRef,data.physical.sealStorageRef)});
test("P124 session reuses cached authenticated reads",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});await result.session.readPlacement("n8");const count=calls.length;await result.session.readPlacement("n8");assert.equal(calls.length,count);assert.ok(calls.filter(x=>x[0]==="getOpaqueObject").length<data.physical.newRecords.length)});
test("P124 stays absent from the real production release manifest",()=>{const manifest=createProductionReleaseManifest({browserRoot:ROOT,serviceRoot:"/pocket-sync/v1"}),paths=manifest.map(e=>e.path);assert.equal(paths.includes("/js/pocket-starling-remote-open-shadow.js"),false);for(const p of ["/js/pocket-sync-local-integration.js","/js/pocket-sync-additional-device.js","/js/pocket-sync-emergency-recovery.js","/js/pocket-sync-production-bootstrap.js"])assert.equal(paths.includes(p),true);assert.equal(fs.readFileSync(path.join(ROOT,"index.html"),"utf8").includes("pocket-starling-remote-open-shadow.js"),false);for(const e of manifest.filter(e=>e.path.endsWith(".js")))assert.equal(fs.readFileSync(path.join(ROOT,`.${e.path}`),"utf8").includes("PocketStarlingRemoteOpenShadow"),false)});
test("P124 does not expose remote records or key material",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});for(const forbidden of ["masterKey","context","resolveStorage","records","handle","bindings"])assert.equal(Object.hasOwn(result.session,forbidden),false)});
test("P124c real P122 publish opens through fresh P120 P124",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(runtime(),data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(result.head.sealRef,data.physical.sealStorageRef);assert.ok(c.PocketStarlingPublicationShadow.createPublisher)});
test("P124c open is lazy bounded and cached",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});const before=calls.length;await result.session.readContent("n20");assert.ok(calls.length-before<data.physical.newRecords.length);const after=calls.length;await result.session.readContent("n20");assert.equal(calls.length,after)});
test("P124c opened reuse proof stages genuine P114 P112 P121 successor",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});const proof=result.session.createReuseProof();assert.equal(Object.isFrozen(proof),true);assert.ok(c.PocketStarlingLogicalEditShadow);assert.ok(c.PocketStarlingStorageShadow.publicationBinding)});
test("P124c failed lazy ID claim preserves index in same session",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(calls[1][1].operationId,"get-object-0");assert.ok(result.session.resolveLogical)});
test("P124c attempted remote GET consumes index",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});await result.session.readContent("n1");assert.equal(new Set(calls.map(x=>x[1].operationId)).size,calls.length)});
test("P124c context and Head authority survive mutation",async()=>{const c=runtime(),data=await fixture(c),calls=[],ctx=context(),result=await opener(c,data,calls).openRemote({masterKey:data.key,context:ctx});ctx.syncedPocketId="changed";await result.session.readContent("n2");assert.equal(calls.every(x=>x[1].syncedPocketId==="p124"),true)});
test("P124c old unadopted Seal cannot override remote Head",async()=>{const c=runtime(),data=await fixture(c),calls=[],result=await opener(c,data,calls).openRemote({masterKey:data.key,context:context()});assert.equal(result.head.sealRef,data.physical.sealStorageRef)});
test("P124c missing Root and lazy object fail at exact boundary",async()=>{const c=runtime(),data=await fixture(c),calls=[];await assert.rejects(opener(c,data,calls,undefined,{request:(route,body)=>route==="readShadowHead"?{status:200,body:{apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId,head:head(1,data.physical.sealStorageRef)}}:{status:200,body:{apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId,storageRef:body.storageRef,present:false,record:null}}}).openRemote({masterKey:data.key,context:context()}),e=>e.code==="remote-open-object-missing")});
test("P124c wrong key and corrupt authenticated material fail closed",async()=>{const c=runtime(),data=await fixture(c),wrapping=await c.PocketSyncCrypto.generateDeviceWrappingKey(),bundle=await c.PocketSyncCrypto.createMasterKeyBundle([{context:{syncedPocketId:"p124",envelopeId:"wrong",envelopeKind:"device",envelopeVersion:1},wrappingKey:wrapping}]),calls=[];await assert.rejects(opener(c,data,calls).openRemote({masterKey:bundle.masterKey,context:context()}));assert.ok(calls.length>=2)});
test("P124c exact empty states are frozen",async()=>{const c=runtime(),data=await fixture(c);for(const current of [null,head(0,null)]){const calls=[],result=await opener(c,data,calls,current).openRemote({masterKey:data.key,context:context()});assert.equal(Object.isFrozen(result),true);assert.equal(calls.length,1)}});
