"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),{webcrypto}=require("node:crypto"),{createProductionReleaseManifest}=require("../sync-service/pocket-sync-production-server.js"),ROOT=path.resolve(__dirname,".."),H="pocket.starling.head.v1",S=["js/pocket-state.js","js/pocket-data.js","js/pocket-outline-persistence-policy.js","js/pocket-editor-metadata.js","js/pocket-pe-import-preserve.js","js/pocket-storage.js","js/pocket-import.js","js/pocket-starling-shadow.js","js/pocket-starling-sequence-shadow.js","js/pocket-starling-placement-shadow.js","js/pocket-starling-bridge-shadow.js","js/pocket-starling-root-shadow.js","js/pocket-starling-object-seal-shadow.js","js/pocket-sync-crypto.js","js/pocket-starling-crypto-shadow.js","js/pocket-starling-storage-shadow.js","js/pocket-starling-head-shadow.js","js/pocket-sync-remote-client.js","js/pocket-starling-logical-edit-shadow.js","js/pocket-starling-publication-shadow.js","js/pocket-starling-remote-open-shadow.js","js/pocket-starling-remote-edit-shadow.js","js/pocket-starling-remote-save-shadow.js"];
const plain=v=>JSON.parse(JSON.stringify(v)),ctx=(syncedPocketId="p129")=>({syncedPocketId}),head=(revision,sealRef)=>({schema:H,revision,sealRef}),ids=p=>(kind,index)=>`${p}-${kind}-${index}`;
function rt(){const c={crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,URL,Date,Math,JSON,Map,Set,WeakMap,WeakSet,Object,Array,String,Number,Boolean,Promise,Error,btoa:v=>Buffer.from(v,"binary").toString("base64"),atob:v=>Buffer.from(v,"base64").toString("binary"),localStorage:{getItem(){},setItem(){},removeItem(){}},document:{body:{classList:{add(){},remove(){},toggle(){}}},getElementById(){},addEventListener(){}},navigator:{clipboard:{}},location:{href:"https://x.test"},indexedDB:null,open(){},close(){},setTimeout,clearTimeout,requestAnimationFrame(){return 1},cancelAnimationFrame(){}};c.window=c;c.globalThis=c;vm.createContext(c);for(const f of S)vm.runInContext(fs.readFileSync(path.join(ROOT,f),"utf8"),c,{filename:f});return c}
function nodes(){return[{id:"source",parentId:"root",order:0,label:"Source"},{id:"dest",parentId:"root",order:1,label:"Destination"},{id:"branch",parentId:"source",order:12,label:"Branch"},...Array.from({length:40},(_,i)=>({id:`s${String(i).padStart(2,"0")}`,parentId:"source",order:i<12?i:i+1,label:`Source ${i}`})),...Array.from({length:900},(_,i)=>({id:`d${String(i).padStart(4,"0")}`,parentId:"branch",order:i,label:`Descendant ${i}`})),...Array.from({length:700},(_,i)=>({id:`u${String(i).padStart(4,"0")}`,parentId:"root",order:100+i,label:`Unrelated ${i}`}))]}
function remote(){return{objects:new Map(),head:head(0,null),calls:[],mode:"normal",readFail:false}}
function svc(c,r){return c.PocketSyncRemoteClient.createObjectHeadService({transport:{async request(route,body){r.calls.push([route,plain(body)]);const common={apiVersion:1,ok:true,operationId:body.operationId,syncedPocketId:body.syncedPocketId};if(route==="putOpaqueObject"){const created=!r.objects.has(body.storageRef);r.objects.set(body.storageRef,body.record);return{status:200,body:{...common,storageRef:body.storageRef,created}}}if(route==="objectPresence")return{status:200,body:{...common,rows:body.storageRefs.map(storageRef=>({storageRef,present:r.objects.has(storageRef)}))}};if(route==="compareAndSetShadowHead"){if(r.head.revision!==body.expectedHead.revision||r.head.sealRef!==body.expectedHead.sealRef)return{status:409,body:{...common,ok:false,reason:"head-conflict"}};const next=head(body.expectedHead.revision+1,body.candidateSealStorageRef);if(r.mode==="apply"){r.head=next;throw new Error("lost")}if(r.mode==="before")throw new Error("lost");r.head=next;return{status:200,body:{...common,head:next}}}if(route==="readShadowHead"){if(r.readFail)throw new Error("lost");return{status:200,body:{...common,head:r.head}}}if(route==="getOpaqueObject"){const record=r.objects.get(body.storageRef);return{status:200,body:{...common,storageRef:body.storageRef,present:!!record,record:record||null}}}throw new Error(route)}}})}
async function setup(){const w=rt(),encoded=w.PocketStarlingBridgeShadow.encode({schema:"portal.mtt.web.v1",writtenAt:"2026-08-30T00:00:00.000Z",nodes:nodes(),tombstones:[],rootExtras:{},dataExtras:{}},{capacity:4}),state=w.PocketStarlingRootShadow.build(encoded.bridge).state,stager=w.PocketStarlingObjectSealShadow.createStager(),logical=w.PocketStarlingObjectSealShadow.stageCandidate(stager,state,{previousSealRef:null});assert.equal(logical.ok,true);const wrapping=await w.PocketSyncCrypto.generateDeviceWrappingKey(),bundle=await w.PocketSyncCrypto.createMasterKeyBundle([{context:{syncedPocketId:"p129",envelopeId:"d",envelopeKind:"device",envelopeVersion:1},wrappingKey:wrapping}]),key=bundle.masterKey,stage=await w.PocketStarlingStorageShadow.stageCandidate({sealRef:logical.stage.sealRef,resolveLogical:r=>stager.store.get(r),masterKey:key,context:ctx()}),r=remote(),pub=w.PocketStarlingPublicationShadow.createPublisher({objectHeadService:svc(w,r),operationIdFactory:ids("gen")});assert.equal((await pub.publishCandidate({stage,expectedHead:head(0,null)})).outcome,"committed");return{w,key,r,stage}}
async function open(f,p){const c=rt(),opened=await c.PocketStarlingRemoteOpenShadow.createRemoteOpener({objectHeadService:svc(c,f.r),operationIdFactory:ids(p)}).openRemote({masterKey:f.key,context:ctx()});return{c,opened}}
async function tx(c,opened,f,p,context=ctx(),factory=ids(p)){return c.PocketStarlingRemoteSaveShadow.createTransaction({opened,masterKey:f.key,context,objectHeadService:svc(c,f.r),operationIdFactory:factory})}
const cas=(r,n)=>r.calls.slice(n).filter(x=>x[0]==="compareAndSetShadowHead"),writes=calls=>calls.some(([x])=>["putOpaqueObject","objectPresence","compareAndSetShadowHead","readShadowHead"].includes(x));
function leaks(...values){for(const value of values)for(const key of ["masterKey","context","opened","session","editor","base","freshBaseProof","candidate","resolver","cache","pending","operationId","operationIdFactory"])assert.equal(Object.hasOwn(value,key),false,key)}
const SECRET_AUTHORITY=["masterKey","context","opened","session","editor","base","freshBaseProof","stage","binding","candidate","resolver","cache","pending","operationId","operationIdFactory","operationIdState","operationIds"];
function surface(value,keys){assert.deepEqual(Object.keys(value),keys);assert.equal(Object.isFrozen(value),true);for(const key of SECRET_AUTHORITY)assert.equal(Object.hasOwn(value,key),false,key)}
async function terminalAcrossSurface(transaction,r){const before=r.calls.length;for(const call of [()=>transaction.savePayload({nodeId:"branch",payload:{label:"blocked"}}),()=>transaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1}),()=>transaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:13}),()=>transaction.saveDelete({nodeId:"branch",fromIndex:12}),()=>transaction.reconcileAmbiguous()])await assert.rejects(call(),error=>error.code==="remote-save-state-invalid");assert.equal(r.calls.length,before)}
const semanticTest=require("./helpers/starling-semantic-test.js"),sessionKeys=new WeakMap(),sessionAuthorities=new WeakMap();
S.push("js/pocket-starling-semantic-authority-shadow.js");
function runtimeWithAuthority(){const c=rt(),edit=c.PocketStarlingRemoteEditShadow,save=c.PocketStarlingRemoteSaveShadow;c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:input=>edit.createEditor({...input,masterKey:sessionKeys.get(input.opened&&input.opened.session)||input.masterKey,semanticAuthority:input.semanticAuthority||sessionAuthorities.get(input.opened&&input.opened.session)})});c.PocketStarlingRemoteSaveShadow=Object.freeze({createTransaction:input=>save.createTransaction({...input,masterKey:sessionKeys.get(input.opened&&input.opened.session)||input.masterKey,semanticAuthority:input.semanticAuthority||sessionAuthorities.get(input.opened&&input.opened.session)})});return c}
async function setup(){const w=runtimeWithAuthority(),encoded=w.PocketStarlingBridgeShadow.encode({schema:"portal.mtt.web.v1",writtenAt:"2026-08-30T00:00:00.000Z",nodes:nodes(),tombstones:[],rootExtras:{},dataExtras:{}},{capacity:4}),state=w.PocketStarlingRootShadow.build(encoded.bridge).state,stager=w.PocketStarlingObjectSealShadow.createStager(),logical=w.PocketStarlingObjectSealShadow.stageCandidate(stager,state,{previousSealRef:null});assert.equal(logical.ok,true);const semantic=await semanticTest.semanticBase(w,{acceptedSealRef:logical.stage.sealRef,resolveLogical:r=>stager.store.get(r),syncedPocketId:"p129"}),key=semantic.masterKey,stage=await w.PocketStarlingStorageShadow.stageCandidate({sealRef:logical.stage.sealRef,resolveLogical:r=>stager.store.get(r),masterKey:key,context:ctx(),semanticAuthority:semantic.semanticAuthority,semanticValidityProof:semantic.semanticValidityProof}),r=remote(),pub=w.PocketStarlingPublicationShadow.createPublisher({objectHeadService:svc(w,r),operationIdFactory:ids("gen")});assert.equal((await pub.publishCandidate({stage,expectedHead:head(0,null)})).outcome,"committed");return{w,key,r,stage,wrappingKey:semantic.envelope.wrappingKey,envelopeContext:semantic.envelope.envelopeContext,record:semantic.envelope.record}}
async function open(f,p){const c=runtimeWithAuthority(),reopened=await c.PocketSyncCrypto.openMasterKeyBundle(f.record,f.wrappingKey,f.envelopeContext,[],{semanticAuthority:true}),opened=await c.PocketStarlingRemoteOpenShadow.createRemoteOpener({objectHeadService:svc(c,f.r),operationIdFactory:ids(p)}).openRemote({masterKey:reopened.masterKey,context:ctx(),semanticAuthority:reopened.semanticAuthority});sessionKeys.set(opened.session,reopened.masterKey);sessionAuthorities.set(opened.session,reopened.semanticAuthority);return{c,opened}}
async function tx(c,opened,f,p,context=ctx(),factory=ids(p)){return c.PocketStarlingRemoteSaveShadow.createTransaction({opened,masterKey:sessionKeys.get(opened&&opened.session),context,semanticAuthority:sessionAuthorities.get(opened&&opened.session),objectHeadService:svc(c,f.r),operationIdFactory:factory})}

test("P129 commits a real cross-parent move once from frozen authority and terminalises every Save method",async()=>{const f=await setup(),o=await open(f,"m"),mutable={outcome:"opened",head:{...o.opened.head},session:o.opened.session},c=ctx(),t=await tx(o.c,mutable,f,"m",c),original=plain(o.opened.head);mutable.head.sealRef="redirected";c.syncedPocketId="redirected";const n=f.r.calls.length,r=await t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:3}),attempt=f.r.calls.slice(n),fresh=await open(f,"m2");assert.deepEqual(Object.keys(t),["savePayload","saveMove","saveReorder","saveDelete","reconcileAmbiguous"]);assert.equal(Object.isFrozen(t),true);assert.deepEqual(Object.keys(r),["outcome","head"]);assert.equal(Object.isFrozen(r),true);assert.equal(cas(f.r,n).length,1);assert.deepEqual(cas(f.r,n)[0][1].expectedHead,original);assert.equal(cas(f.r,n)[0][1].candidateSealStorageRef,r.head.sealRef);assert.equal(f.r.calls.slice(n,n+attempt.length).some(x=>x[0]==="readShadowHead"),false);assert.deepEqual(plain(f.r.head),plain(r.head));assert.equal((await fresh.opened.session.readPlacement("branch")).parentId,"dest");const after=f.r.calls.length;for(const call of [()=>t.savePayload({nodeId:"branch",payload:{}}),()=>t.saveMove({nodeId:"branch",fromIndex:0,newParentId:"source",toIndex:0}),()=>t.saveReorder({nodeId:"branch",fromIndex:0,toIndex:1}),()=>t.saveDelete({nodeId:"branch",fromIndex:0}),()=>t.reconcileAmbiguous()])await assert.rejects(call(),e=>e.code==="remote-save-state-invalid");assert.equal(f.r.calls.length,after);leaks(o.c.PocketStarlingRemoteSaveShadow,t,r)});

test("P129 commits real P116 reorder material and a reopened equivalent reorder is unchanged",async()=>{const f=await setup(),o=await open(f,"r"),real=o.c.PocketStarlingRemoteEditShadow;let captured;o.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await real.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:editor.prepareMove,prepareReorder:async value=>{const result=await editor.prepareReorder(value);if(result.outcome==="prepared")captured=result;return result}})}});const t=await tx(o.c,o.opened,f,"r"),n=f.r.calls.length,r=await t.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27}),fresh=await open(f,"r2"),next=await fresh.c.PocketStarlingRemoteEditShadow.createEditor({opened:fresh.opened,masterKey:f.key,context:ctx()}),before=f.r.calls.length,u=await next.prepareReorder({nodeId:"branch",fromIndex:26,toIndex:26});assert.ok(captured);assert.equal(cas(f.r,n).length,1);assert.equal(cas(f.r,n)[0][1].candidateSealStorageRef,captured.stage.sealStorageRef);assert.equal(cas(f.r,n)[0][1].expectedHead.sealRef,captured.binding.expectedSealStorageRef);assert.equal(f.r.head.sealRef,captured.stage.sealStorageRef);assert.deepEqual(plain(u),{outcome:"unchanged"});assert.equal(f.r.calls.slice(before).some(x=>x[0]!=="getOpaqueObject"),false);assert.equal(r.outcome,"committed")});

test("P129 no-change and lower-layer structural failures publish nothing and preserve ready state",async()=>{const f=await setup(),o=await open(f,"n"),t=await tx(o.c,o.opened,f,"n"),n=f.r.calls.length,u=await t.saveReorder({nodeId:"branch",fromIndex:12,toIndex:12}),same=await t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"source",toIndex:1}),bad=await t.saveReorder({nodeId:"branch",fromIndex:999,toIndex:1});assert.deepEqual(plain(u),{outcome:"unchanged"});assert.equal(Object.isFrozen(u),true);assert.equal(same.reason,"same-parent-reorder-not-in-scope");assert.equal(bad.reason,"placement-membership-mismatch");assert.equal(writes(f.r.calls.slice(n)),false);const committed=await t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2});assert.equal(committed.outcome,"committed");assert.equal(cas(f.r,n).length,1)});

test("P129 structural stale conflict is one-CAS terminal truth",async()=>{const f=await setup(),a=await open(f,"a"),b=await open(f,"b"),stale=await tx(a.c,a.opened,f,"stale"),winner=await tx(b.c,b.opened,f,"winner"),won=await winner.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2}),n=f.r.calls.length,lost=await stale.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27});assert.deepEqual(plain(lost),{outcome:"conflict",reason:"head-conflict"});assert.equal(cas(f.r,n).length,1);assert.equal(f.r.calls.slice(n).some(x=>x[0]==="readShadowHead"),false);assert.equal(f.r.head.sealRef,won.head.sealRef);const after=f.r.calls.length;await assert.rejects(stale.reconcileAmbiguous(),e=>e.code==="remote-save-state-invalid");assert.equal(f.r.calls.length,after)});

test("P129 ambiguous structural commit reconciles explicitly without completing the captured stage",async()=>{const f=await setup(),o=await open(f,"ac"),real=o.c.PocketStarlingRemoteEditShadow;let captured;o.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await real.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:async value=>{const result=await editor.prepareMove(value);if(result.outcome==="prepared")captured=result.stage;return result},prepareReorder:editor.prepareReorder})}});const t=await tx(o.c,o.opened,f,"ac"),n=f.r.calls.length;f.r.mode="apply";const a=await t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2});assert.deepEqual(plain(a),{outcome:"ambiguous"});assert.equal(Object.isFrozen(a),true);assert.equal(cas(f.r,n).length,1);assert.equal(f.r.calls.slice(n).some(x=>x[0]==="readShadowHead"),false);const blocked=f.r.calls.length;for(const call of [()=>t.savePayload({nodeId:"branch",payload:{}}),()=>t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2}),()=>t.saveReorder({nodeId:"branch",fromIndex:12,toIndex:13})])await assert.rejects(call(),e=>e.code==="remote-save-state-invalid");assert.equal(f.r.calls.length,blocked);f.r.mode="normal";const b=f.r.calls.length,r=await t.reconcileAmbiguous();assert.deepEqual(plain(r),{outcome:"committed",examined:1});assert.equal(f.r.calls.slice(b).every(x=>["readShadowHead","getOpaqueObject"].includes(x[0])),true);assert.equal(cas(f.r,n).length,1);await assert.rejects(o.c.PocketStarlingStorageShadow.stageCandidate({sealRef:"proof-ref:v1:candidate-seal:00000000",resolveLogical(){throw new Error("traverse")},masterKey:f.key,context:ctx(),baseStage:captured}),e=>e.code==="base-stage-incomplete");assert.equal((await (await open(f,"ac2")).opened.session.readPlacement("branch")).parentId,"dest")});

test("P129 structural not-committed and UNKNOWN retain exact caller-driven state",async()=>{const f=await setup(),o=await open(f,"nc"),t=await tx(o.c,o.opened,f,"nc"),original=plain(o.opened.head),n=f.r.calls.length;f.r.mode="before";assert.deepEqual(plain(await t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2})),{outcome:"ambiguous"});f.r.mode="normal";assert.deepEqual(plain(await t.reconcileAmbiguous()),{outcome:"not-committed",examined:0});assert.deepEqual(plain(f.r.head),original);assert.equal(cas(f.r,n).length,1);const g=await setup(),q=await open(g,"u"),u=await tx(q.c,q.opened,g,"u"),m=g.r.calls.length;g.r.mode="apply";await u.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27});g.r.mode="normal";g.r.readFail=true;assert.deepEqual(plain(await u.reconcileAmbiguous()),{outcome:"unknown",examined:0});const blocked=g.r.calls.length;await assert.rejects(u.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1}),e=>e.code==="remote-save-state-invalid");assert.equal(g.r.calls.length,blocked);g.r.readFail=false;assert.deepEqual(plain(await u.reconcileAmbiguous()),{outcome:"committed",examined:1});assert.equal(cas(g.r,m).length,1)});

test("P129 local P122 P123 errors and malformed structural inputs preserve the accepted state machine",async()=>{const f=await setup(),o=await open(f,"lf"),real=o.c.PocketStarlingRemoteEditShadow;let calls=0;o.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await real.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:async value=>{calls+=1;return editor.prepareMove(value)},prepareReorder:async value=>{calls+=1;return editor.prepareReorder(value)}})}});const t=await tx(o.c,o.opened,f,"lf",ctx(),()=>" "),before=f.r.calls.length;for(const value of [{nodeId:"branch",fromIndex:12,newParentId:"dest"},{nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1,stage:"x"}])await assert.rejects(t.saveMove(value),e=>e.code==="remote-save-input-invalid");await assert.rejects(t.saveReorder({nodeId:"branch",fromIndex:12,toIndex:1,freshBaseProof:"x"}),e=>e.code==="remote-save-input-invalid");assert.equal(calls,0);assert.equal(f.r.calls.length,before);await assert.rejects(t.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1}),e=>e.code==="publication-operation-id-invalid");const after=f.r.calls.length;await assert.rejects(t.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27}),e=>e.code==="remote-save-state-invalid");assert.equal(f.r.calls.length,after);const g=await setup(),q=await open(g,"p123");let bad=false;const u=await tx(q.c,q.opened,g,"p123",ctx(),(k,i)=>bad&&k==="read-head"?" ":`p-${k}-${i}`);g.r.mode="apply";await u.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1});g.r.mode="normal";bad=true;const io=g.r.calls.length;await assert.rejects(u.reconcileAmbiguous(),e=>e.code==="publication-operation-id-invalid");assert.equal(g.r.calls.length,io);bad=false;assert.deepEqual(plain(await u.reconcileAmbiguous()),{outcome:"committed",examined:1})});

test("P129 remains dormant with narrow frozen public values",()=>{const c=rt(),manifest=createProductionReleaseManifest({browserRoot:ROOT,serviceRoot:"/pocket-sync/v1"});assert.deepEqual(Object.keys(c.PocketStarlingRemoteSaveShadow),["createTransaction"]);assert.equal(Object.isFrozen(c.PocketStarlingRemoteSaveShadow),true);assert.equal(manifest.some(x=>x.path==="/js/pocket-starling-remote-save-shadow.js"),false);for(const entry of manifest.filter(x=>x.path.endsWith(".js")))assert.equal(fs.readFileSync(path.join(ROOT,`.${entry.path}`),"utf8").includes("PocketStarlingRemoteSaveShadow"),false,entry.path)});

test("P129a preserves frozen Pocket and Head authority through P122 and P123 after caller mutation",async()=>{
  const committedFixture=await setup(),committedOpen=await open(committedFixture,"p129a-authority-commit"),committedReal=committedOpen.c.PocketStarlingRemoteEditShadow;
  let committedPrepared;
  committedOpen.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await committedReal.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:async value=>{const result=await editor.prepareMove(value);if(result.outcome==="prepared")committedPrepared=result;return result},prepareReorder:editor.prepareReorder})}});
  const committedOpened={outcome:"opened",head:{...committedOpen.opened.head},session:committedOpen.opened.session},committedContext=ctx(),committedOriginal=plain(committedOpen.opened.head),committedTransaction=await tx(committedOpen.c,committedOpened,committedFixture,"p129a-authority-commit",committedContext),committedBefore=committedFixture.r.calls.length;
  committedOpened.head.revision=91;committedOpened.head.sealRef="caller-redirected-seal";committedContext.syncedPocketId="caller-redirected-pocket";
  const committed=await committedTransaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:3}),committedRequests=committedFixture.r.calls.slice(committedBefore).filter(([route])=>["putOpaqueObject","objectPresence","compareAndSetShadowHead"].includes(route)),committedCas=cas(committedFixture.r,committedBefore);
  assert.ok(committedPrepared);assert.equal(committed.outcome,"committed");assert.ok(committedRequests.length>0);assert.equal(committedRequests.every(([,body])=>body.syncedPocketId==="p129"),true);assert.equal(committedCas.length,1);assert.deepEqual(committedCas[0][1].expectedHead,committedOriginal);assert.deepEqual(plain(committedPrepared.expectedHead),committedOriginal);assert.equal(committedCas[0][1].candidateSealStorageRef,committedPrepared.stage.sealStorageRef);assert.equal(committedPrepared.binding.candidateSealStorageRef,committedPrepared.stage.sealStorageRef);

  const ambiguousFixture=await setup(),ambiguousOpen=await open(ambiguousFixture,"p129a-authority-ambiguous"),ambiguousReal=ambiguousOpen.c.PocketStarlingRemoteEditShadow;
  let ambiguousPrepared;
  ambiguousOpen.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await ambiguousReal.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:editor.prepareMove,prepareReorder:async value=>{const result=await editor.prepareReorder(value);if(result.outcome==="prepared")ambiguousPrepared=result;return result}})}});
  const ambiguousOpened={outcome:"opened",head:{...ambiguousOpen.opened.head},session:ambiguousOpen.opened.session},ambiguousContext=ctx(),ambiguousOriginal=plain(ambiguousOpen.opened.head),ambiguousTransaction=await tx(ambiguousOpen.c,ambiguousOpened,ambiguousFixture,"p129a-authority-ambiguous",ambiguousContext),ambiguousBefore=ambiguousFixture.r.calls.length;
  ambiguousOpened.head.revision=92;ambiguousOpened.head.sealRef="save-redirected-seal";ambiguousContext.syncedPocketId="save-redirected-pocket";ambiguousFixture.r.mode="apply";
  assert.deepEqual(plain(await ambiguousTransaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27})),{outcome:"ambiguous"});assert.ok(ambiguousPrepared);assert.equal(cas(ambiguousFixture.r,ambiguousBefore).length,1);assert.deepEqual(cas(ambiguousFixture.r,ambiguousBefore)[0][1].expectedHead,ambiguousOriginal);assert.equal(cas(ambiguousFixture.r,ambiguousBefore)[0][1].candidateSealStorageRef,ambiguousPrepared.stage.sealStorageRef);
  ambiguousOpened.head.revision=93;ambiguousOpened.head.sealRef="reconcile-redirected-seal";ambiguousContext.syncedPocketId="reconcile-redirected-pocket";ambiguousFixture.r.mode="normal";const reconcileBefore=ambiguousFixture.r.calls.length,reconciled=await ambiguousTransaction.reconcileAmbiguous(),reconcileRequests=ambiguousFixture.r.calls.slice(reconcileBefore);
  assert.deepEqual(plain(reconciled),{outcome:"committed",examined:1});assert.ok(reconcileRequests.length>=2);assert.equal(reconcileRequests.every(([route,body])=>["readShadowHead","getOpaqueObject"].includes(route)&&body.syncedPocketId==="p129"),true);assert.equal(reconcileRequests.filter(([route])=>route==="getOpaqueObject").every(([,body])=>body.storageRef===ambiguousPrepared.stage.sealStorageRef),true);assert.deepEqual(plain(ambiguousPrepared.expectedHead),ambiguousOriginal);assert.equal(ambiguousPrepared.binding.expectedSealStorageRef,ambiguousOriginal.sealRef);assert.equal(cas(ambiguousFixture.r,ambiguousBefore).length,1);
});

test("P129a rejects the full structural caller-authority matrix before P128 callbacks or remote I/O",async()=>{
  const f=await setup(),o=await open(f,"p129a-matrix"),realEdit=o.c.PocketStarlingRemoteEditShadow,realStorage=o.c.PocketStarlingStorageShadow;
  let moveCallbacks=0,reorderCallbacks=0,stagingCalls=0;
  o.c.PocketStarlingRemoteEditShadow=Object.freeze({createEditor:async input=>{const editor=await realEdit.createEditor(input);return Object.freeze({preparePayloadEdit:editor.preparePayloadEdit,prepareMove:async value=>{moveCallbacks+=1;return editor.prepareMove(value)},prepareReorder:async value=>{reorderCallbacks+=1;return editor.prepareReorder(value)}})}});
  o.c.PocketStarlingStorageShadow=Object.freeze({...realStorage,stageCandidate:async input=>{stagingCalls+=1;return realStorage.stageCandidate(input)}});
  const transaction=await tx(o.c,o.opened,f,"p129a-matrix"),before=f.r.calls.length,move={nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1},reorder={nodeId:"branch",fromIndex:12,toIndex:27},fields=["expectedHead","sealRef","stage","binding","baseStage","freshBaseProof","acceptedSealStorageRef","candidateSealStorageRef","newLogicalRefs"];
  for(const field of fields){await assert.rejects(transaction.saveMove({...move,[field]:field==="newLogicalRefs"?[]:"injected"}),error=>error.code==="remote-save-input-invalid");await assert.rejects(transaction.saveReorder({...reorder,[field]:field==="newLogicalRefs"?[]:"injected"}),error=>error.code==="remote-save-input-invalid")}
  await assert.rejects(transaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest"}),error=>error.code==="remote-save-input-invalid");await assert.rejects(transaction.saveReorder({nodeId:"branch",fromIndex:12}),error=>error.code==="remote-save-input-invalid");
  assert.equal(moveCallbacks,0);assert.equal(reorderCallbacks,0);assert.equal(stagingCalls,0);assert.equal(f.r.calls.length,before);
});

test("P129a not-committed structural ambiguity preserves unadopted objects and becomes fully terminal",async()=>{
  const f=await setup(),o=await open(f,"p129a-not-committed"),transaction=await tx(o.c,o.opened,f,"p129a-not-committed"),original=plain(o.opened.head),before=f.r.calls.length;
  f.r.mode="before";assert.deepEqual(plain(await transaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2})),{outcome:"ambiguous"});const puts=f.r.calls.slice(before).filter(([route])=>route==="putOpaqueObject");assert.ok(puts.length>0);assert.equal(cas(f.r,before).length,1);
  f.r.mode="normal";const reconcileBefore=f.r.calls.length,reconciled=await transaction.reconcileAmbiguous(),reconcileCalls=f.r.calls.slice(reconcileBefore);
  assert.deepEqual(plain(reconciled),{outcome:"not-committed",examined:0});assert.equal(Object.isFrozen(reconciled),true);assert.deepEqual(plain(f.r.head),original);assert.equal(puts.some(([,body])=>f.r.objects.has(body.storageRef)),true);assert.ok(reconcileCalls.length>0);assert.equal(reconcileCalls.every(([route])=>route==="readShadowHead"),true);assert.equal(cas(f.r,before).length,1);await terminalAcrossSurface(transaction,f.r);
});

test("P129a UNKNOWN structural reconciliation blocks every Save until explicit recheck then terminalises",async()=>{
  const f=await setup(),o=await open(f,"p129a-unknown"),transaction=await tx(o.c,o.opened,f,"p129a-unknown"),before=f.r.calls.length;
  f.r.mode="apply";assert.deepEqual(plain(await transaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27})),{outcome:"ambiguous"});f.r.mode="normal";f.r.readFail=true;const unknownBefore=f.r.calls.length,unknown=await transaction.reconcileAmbiguous();assert.deepEqual(plain(unknown),{outcome:"unknown",examined:0});assert.equal(f.r.calls.slice(unknownBefore).every(([route])=>route==="readShadowHead"),true);
  const blocked=f.r.calls.length;for(const call of [()=>transaction.savePayload({nodeId:"branch",payload:{label:"blocked"}}),()=>transaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1}),()=>transaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:13})])await assert.rejects(call(),error=>error.code==="remote-save-state-invalid");assert.equal(f.r.calls.length,blocked);
  f.r.readFail=false;const recheckBefore=f.r.calls.length,reconciled=await transaction.reconcileAmbiguous(),recheckCalls=f.r.calls.slice(recheckBefore);assert.deepEqual(plain(reconciled),{outcome:"committed",examined:1});assert.equal(recheckCalls.every(([route])=>["readShadowHead","getOpaqueObject"].includes(route)),true);assert.equal(recheckCalls.some(([route])=>["putOpaqueObject","objectPresence","compareAndSetShadowHead"].includes(route)),false);assert.equal(cas(f.r,before).length,1);await terminalAcrossSurface(transaction,f.r);
});

test("P129a definite structural commit and conflict are fully terminal across the expanded transaction surface",async()=>{
  const committedFixture=await setup(),committedOpen=await open(committedFixture,"p129a-terminal-commit"),committedTransaction=await tx(committedOpen.c,committedOpen.opened,committedFixture,"p129a-terminal-commit"),committedBefore=committedFixture.r.calls.length,committed=await committedTransaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27}),committedAttempt=committedFixture.r.calls.slice(committedBefore),committedFirstPut=committedAttempt.findIndex(([route])=>route==="putOpaqueObject"),committedCasIndex=committedAttempt.findIndex(([route])=>route==="compareAndSetShadowHead");
  assert.deepEqual(Object.keys(committed),["outcome","head"]);assert.equal(Object.isFrozen(committed),true);assert.equal(committed.outcome,"committed");assert.equal(cas(committedFixture.r,committedBefore).length,1);assert.ok(committedFirstPut>=0&&committedCasIndex>committedFirstPut);assert.equal(committedAttempt.slice(committedFirstPut,committedCasIndex+1).some(([route])=>["readShadowHead","getOpaqueObject"].includes(route)),false);assert.equal(committedAttempt.some(([route])=>route==="readShadowHead"),false);await terminalAcrossSurface(committedTransaction,committedFixture.r);

  const conflictFixture=await setup(),staleOpen=await open(conflictFixture,"p129a-terminal-stale"),winnerOpen=await open(conflictFixture,"p129a-terminal-winner"),stale=await tx(staleOpen.c,staleOpen.opened,conflictFixture,"p129a-terminal-stale"),winner=await tx(winnerOpen.c,winnerOpen.opened,conflictFixture,"p129a-terminal-winner"),won=await winner.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2}),competingHead=plain(conflictFixture.r.head),conflictBefore=conflictFixture.r.calls.length,conflict=await stale.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27}),conflictAttempt=conflictFixture.r.calls.slice(conflictBefore),conflictFirstPut=conflictAttempt.findIndex(([route])=>route==="putOpaqueObject"),conflictCasIndex=conflictAttempt.findIndex(([route])=>route==="compareAndSetShadowHead");
  assert.deepEqual(plain(conflict),{outcome:"conflict",reason:"head-conflict"});assert.equal(Object.isFrozen(conflict),true);assert.equal(cas(conflictFixture.r,conflictBefore).length,1);assert.ok(conflictFirstPut>=0&&conflictCasIndex>conflictFirstPut);assert.equal(conflictAttempt.slice(conflictFirstPut,conflictCasIndex+1).some(([route])=>["readShadowHead","getOpaqueObject"].includes(route)),false);assert.equal(conflictAttempt.some(([route])=>route==="readShadowHead"),false);assert.deepEqual(plain(conflictFixture.r.head),competingHead);assert.deepEqual(plain(conflictFixture.r.head),plain(won.head));await terminalAcrossSurface(stale,conflictFixture.r);
});

test("P129a exact structural result surfaces are frozen and leak no internal authority",async()=>{
  const committedFixture=await setup(),committedOpen=await open(committedFixture,"p129a-surface-commit"),transaction=await tx(committedOpen.c,committedOpen.opened,committedFixture,"p129a-surface-commit"),unchanged=await transaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:12}),committed=await transaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2});
  const reconciledFixture=await setup(),reconciledOpen=await open(reconciledFixture,"p129a-surface-reconciled"),reconciledTransaction=await tx(reconciledOpen.c,reconciledOpen.opened,reconciledFixture,"p129a-surface-reconciled");reconciledFixture.r.mode="apply";const ambiguous=await reconciledTransaction.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27});reconciledFixture.r.mode="normal";const committedReconciliation=await reconciledTransaction.reconcileAmbiguous();
  const notCommittedFixture=await setup(),notCommittedOpen=await open(notCommittedFixture,"p129a-surface-not-committed"),notCommittedTransaction=await tx(notCommittedOpen.c,notCommittedOpen.opened,notCommittedFixture,"p129a-surface-not-committed");notCommittedFixture.r.mode="before";await notCommittedTransaction.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:1});notCommittedFixture.r.mode="normal";const notCommittedReconciliation=await notCommittedTransaction.reconcileAmbiguous();
  const conflictFixture=await setup(),staleOpen=await open(conflictFixture,"p129a-surface-stale"),winnerOpen=await open(conflictFixture,"p129a-surface-winner"),stale=await tx(staleOpen.c,staleOpen.opened,conflictFixture,"p129a-surface-stale"),winner=await tx(winnerOpen.c,winnerOpen.opened,conflictFixture,"p129a-surface-winner");await winner.saveMove({nodeId:"branch",fromIndex:12,newParentId:"dest",toIndex:2});const conflict=await stale.saveReorder({nodeId:"branch",fromIndex:12,toIndex:27});
  assert.equal(unchanged.outcome,"unchanged");assert.equal(ambiguous.outcome,"ambiguous");assert.equal(committed.outcome,"committed");assert.equal(conflict.outcome,"conflict");assert.equal(committedReconciliation.outcome,"committed");assert.equal(notCommittedReconciliation.outcome,"not-committed");
  for(const [value,keys]of [[committedOpen.c.PocketStarlingRemoteSaveShadow,["createTransaction"]],[transaction,["savePayload","saveMove","saveReorder","saveDelete","reconcileAmbiguous"]],[unchanged,["outcome"]],[ambiguous,["outcome"]],[committed,["outcome","head"]],[conflict,["outcome","reason"]],[committedReconciliation,["outcome","examined"]],[notCommittedReconciliation,["outcome","examined"]]])surface(value,keys);
});

test("P129a retains real production dormancy after proof closure",()=>{
  const c=rt(),manifest=createProductionReleaseManifest({browserRoot:ROOT,serviceRoot:"/pocket-sync/v1"});assert.deepEqual(Object.keys(c.PocketStarlingRemoteSaveShadow),["createTransaction"]);assert.equal(Object.isFrozen(c.PocketStarlingRemoteSaveShadow),true);assert.equal(manifest.some(entry=>entry.path==="/js/pocket-starling-remote-save-shadow.js"),false);for(const entry of manifest.filter(value=>value.path.endsWith(".js")))assert.equal(fs.readFileSync(path.join(ROOT,`.${entry.path}`),"utf8").includes("PocketStarlingRemoteSaveShadow"),false,entry.path);
});
