"use strict";

const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), vm = require("node:vm"), { webcrypto } = require("node:crypto"), ROOT = path.resolve(__dirname, "..");
const SCRIPTS = ["js/pocket-state.js", "js/pocket-data.js", "js/pocket-outline-persistence-policy.js", "js/pocket-editor-metadata.js", "js/pocket-pe-import-preserve.js", "js/pocket-storage.js", "js/pocket-import.js", "js/pocket-starling-shadow.js", "js/pocket-starling-sequence-shadow.js", "js/pocket-starling-placement-shadow.js", "js/pocket-starling-bridge-shadow.js", "js/pocket-starling-root-shadow.js", "js/pocket-starling-object-seal-shadow.js", "js/pocket-sync-crypto.js", "js/pocket-starling-crypto-shadow.js", "js/pocket-starling-storage-shadow.js", "js/pocket-starling-head-shadow.js", "js/pocket-sync-remote-client.js", "js/pocket-starling-logical-edit-shadow.js", "js/pocket-starling-semantic-authority-shadow.js", "js/pocket-starling-remote-open-shadow.js"];
function runtime() { const c = { crypto: webcrypto, TextEncoder, TextDecoder, Uint8Array, ArrayBuffer, URL, Date, Math, JSON, Map, Set, WeakMap, WeakSet, Object, Array, String, Number, Boolean, Promise, Error, btoa: v => Buffer.from(v, "binary").toString("base64"), atob: v => Buffer.from(v, "base64").toString("binary"), localStorage: { getItem() {}, setItem() {}, removeItem() {} }, document: { body: { classList: { add() {}, remove() {}, toggle() {} } }, getElementById() {}, addEventListener() {} }, navigator: { clipboard: {} }, location: { href: "https://example.test" }, indexedDB: null, open() {}, close() {}, setTimeout() { return 1; }, clearTimeout() {}, requestAnimationFrame() { return 1; }, cancelAnimationFrame() {} }; c.window = c; c.globalThis = c; vm.createContext(c); for (const file of SCRIPTS) vm.runInContext(fs.readFileSync(path.join(ROOT, file), "utf8"), c, { filename: file }); return c; }
function binding(seal, pocket) { return Object.freeze({ syncedPocketId: pocket, logicalSealRef: seal.sealRef, logicalRootRef: seal.sealObject.rootRef, previousLogicalSealRef: seal.sealObject.previousSealRef, logicalSealSchema: "pocket.starling.candidate-seal.v1", logicalRootSchema: "pocket.starling.logical-root.v1", logicalObjectSchema: "pocket.starling.logical-object.v1", sequenceSchema: "pocket.starling.sequence-page.v2", placementGeneration: "pocket.starling.placement-relation.v1" }); }
function stage(c) { const encoded = c.PocketStarlingBridgeShadow.encode({ schema: "portal.mtt.web.v1", writtenAt: "2026-08-31T00:00:00.000Z", nodes: [{ id: "n", parentId: "root", order: 0, label: "N", value: 1 }], tombstones: [], rootExtras: {}, dataExtras: {} }, { capacity: 4 }), state = c.PocketStarlingRootShadow.build(encoded.bridge).state, stager = c.PocketStarlingObjectSealShadow.createStager(), staged = c.PocketStarlingObjectSealShadow.stageCandidate(stager, state, { previousSealRef: null }); assert.equal(encoded.ok, true); assert.equal(staged.ok, true); return { stager, seal: staged.stage }; }

test("P132l binds issuer proof, attestation fields, MAC, and same-master envelope authority exactly", async () => {
  const writer = runtime(), pocket = "p132l-pocket", current = stage(writer), wrapping = await writer.PocketSyncCrypto.generateDeviceWrappingKey(), sourceContext = { syncedPocketId: pocket, envelopeId: "source", envelopeKind: "device", envelopeVersion: 1 }, bundle = await writer.PocketSyncCrypto.createMasterKeyBundle([{ context: sourceContext, wrappingKey: wrapping }], { semanticAuthority: true }), audit = writer.PocketStarlingObjectSealShadow.auditCandidateSeal(current.seal.sealRef, ref => current.stager.store.get(ref)), provenance = writer.PocketStarlingObjectSealShadow.semanticAuditProvenance(audit), issued = await writer.PocketStarlingSemanticAuthorityShadow.issueInitial({ authority: bundle.semanticAuthority, auditProof: provenance }), exact = binding(current.seal, pocket), record = writer.PocketStarlingSemanticAuthorityShadow.attestationForStage({ authority: bundle.semanticAuthority, proof: issued.proof, binding: exact });
  assert.equal(audit.ok, true); assert.equal(issued.ok, true); assert.ok(record);
  const transferWrapping = await writer.PocketSyncCrypto.generateDeviceWrappingKey(), transferContext = { syncedPocketId: pocket, envelopeId: "transfer", envelopeKind: "device", envelopeVersion: 1 }, reopened = await writer.PocketSyncCrypto.openMasterKeyBundle(bundle.envelopes[0].record, wrapping, sourceContext, [{ context: transferContext, wrappingKey: transferWrapping }], { semanticAuthority: true }), reader = runtime(), transferred = await reader.PocketSyncCrypto.openMasterKeyBundle(reopened.envelopes[0].record, transferWrapping, transferContext, [], { semanticAuthority: true });
  assert.equal((await reader.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: transferred.semanticAuthority, semanticValidity: record, binding: exact })).ok, true);
  const other = await reader.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "other", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: await reader.PocketSyncCrypto.generateDeviceWrappingKey() }], { semanticAuthority: true });
  assert.equal((await reader.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: other.semanticAuthority, semanticValidity: record, binding: exact })).ok, false);
  const mutations = ["syncedPocketId", "logicalSealRef", "logicalRootRef", "previousLogicalSealRef", "logicalSealSchema", "logicalRootSchema", "logicalObjectSchema", "sequenceSchema", "placementGeneration"];
  for (const field of mutations) { const changed = { ...record, [field]: field === "previousLogicalSealRef" ? "proof-ref:v1:candidate-seal:changed" : "changed" }; assert.equal((await reader.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: transferred.semanticAuthority, semanticValidity: changed, binding: exact })).ok, false, field); }
  for (const changed of [{ ...record, schema: "wrong" }, { ...record, algorithm: "wrong" }, { ...record, tag: "bad" }, { ...record, tag: `${record.tag.slice(0, -1)}${record.tag.endsWith("A") ? "B" : "A"}` }, (() => { const value = { ...record }; delete value.tag; return value; })(), { ...record, extra: true }]) assert.equal((await reader.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: transferred.semanticAuthority, semanticValidity: changed, binding: exact })).ok, false);
  const physical = await writer.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context: { syncedPocketId: pocket }, semanticAuthority: bundle.semanticAuthority, semanticValidityProof: issued.proof });
  await assert.rejects(writer.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context: { syncedPocketId: pocket }, semanticAuthority: bundle.semanticAuthority, semanticValidityProof: { ...record } }), error => error.code === "semantic-validity-input-invalid");
  assert.ok(physical.sealStorageRef);
});

test("P132l binds successor induction to the authenticated base and authority", async () => {
  const c = runtime(), pocket = "p132l-induction", first = stage(c), second = stage(c), wrapping = await c.PocketSyncCrypto.generateDeviceWrappingKey(), bundle = await c.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "d", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: wrapping }], { semanticAuthority: true });
  async function admit(value) { const audit = c.PocketStarlingObjectSealShadow.auditCandidateSeal(value.seal.sealRef, ref => value.stager.store.get(ref)), proof = c.PocketStarlingObjectSealShadow.semanticAuditProvenance(audit), issued = await c.PocketStarlingSemanticAuthorityShadow.issueInitial({ authority: bundle.semanticAuthority, auditProof: proof }), accepted = await c.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: bundle.semanticAuthority, semanticValidity: c.PocketStarlingSemanticAuthorityShadow.attestationForStage({ authority: bundle.semanticAuthority, proof: issued.proof, binding: binding(value.seal, pocket) }), binding: binding(value.seal, pocket) }), result = await c.PocketStarlingLogicalEditShadow.createBase({ acceptedSealRef: value.seal.sealRef, resolveLogical: ref => value.stager.store.get(ref), syncedPocketId: pocket, semanticAuthority: bundle.semanticAuthority, semanticBaseProof: accepted.semanticBaseProof }); return { result, proof: accepted.semanticBaseProof }; }
  const a = await admit(first), b = await admit(second), edit = await c.PocketStarlingLogicalEditShadow.editPayload(a.result.base, "n", { label: "Changed", value: 2 }), issued = await c.PocketStarlingSemanticAuthorityShadow.issueSuccessor({ authority: bundle.semanticAuthority, semanticBaseProof: a.proof, candidate: edit.candidate });
  assert.equal(a.result.ok, true); assert.equal(b.result.ok, true); assert.equal(edit.changed, true); assert.equal(issued.ok, true); assert.equal(JSON.parse(edit.candidate.resolveLogical(edit.candidate.sealRef)).previousSealRef, first.seal.sealRef);
  assert.equal((await c.PocketStarlingSemanticAuthorityShadow.issueSuccessor({ authority: bundle.semanticAuthority, semanticBaseProof: b.proof, candidate: edit.candidate })).ok, false);
  const other = await c.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "other", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: await c.PocketSyncCrypto.generateDeviceWrappingKey() }], { semanticAuthority: true });
  assert.equal((await c.PocketStarlingSemanticAuthorityShadow.issueSuccessor({ authority: other.semanticAuthority, semanticBaseProof: a.proof, candidate: edit.candidate })).ok, false);
  const unchanged = await c.PocketStarlingLogicalEditShadow.editPayload(a.result.base, "n", { label: "N", value: 1 }); assert.equal(unchanged.changed, false); assert.equal(unchanged.candidate, undefined);
});

test("P132l physical authentication precedes semantic missing failure and equal payload corruption never no-changes", async () => {
  const c = runtime(), pocket = "p132l-open", current = stage(c), wrapping = await c.PocketSyncCrypto.generateDeviceWrappingKey(), context = { syncedPocketId: pocket }, bundle = await c.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "d", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: wrapping }], { semanticAuthority: true }), audit = c.PocketStarlingObjectSealShadow.auditCandidateSeal(current.seal.sealRef, ref => current.stager.store.get(ref)), issued = await c.PocketStarlingSemanticAuthorityShadow.issueInitial({ authority: bundle.semanticAuthority, auditProof: c.PocketStarlingObjectSealShadow.semanticAuditProvenance(audit) }), attested = await c.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context, semanticAuthority: bundle.semanticAuthority, semanticValidityProof: issued.proof }), legacy = await c.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context }), records = new Map(legacy.newRecords.map(entry => [entry.storageRef, entry.record]));
  const opener = c.PocketStarlingRemoteOpenShadow.createRemoteOpener({ objectHeadService: { async readShadowHead() { return { head: { schema: "pocket.starling.head.v1", revision: 1, sealRef: legacy.sealStorageRef } }; }, async getOpaqueObject({ storageRef }) { return { present: records.has(storageRef), record: records.get(storageRef) }; } }, operationIdFactory: (kind, index) => `${kind}-${index}` });
  await assert.rejects(opener.openRemote({ masterKey: bundle.masterKey, context, semanticAuthority: bundle.semanticAuthority }), error => error.code === "semantic-validity-missing");
  const resolver = await c.PocketStarlingStorageShadow.createResolver({ acceptedSealStorageRef: attested.sealStorageRef, acceptedBaseComplete: true, masterKey: bundle.masterKey, context, resolveStorage: ref => new Map(attested.newRecords.map(entry => [entry.storageRef, entry.record])).get(ref) }), accepted = await resolver.openAccepted(), semantic = await c.PocketStarlingSemanticAuthorityShadow.authenticate({ authority: bundle.semanticAuthority, semanticValidity: resolver.semanticValidity(), binding: Object.freeze({ syncedPocketId: pocket, logicalSealRef: resolver.acceptedSealRef, logicalRootRef: accepted.handle.seal.rootRef, previousLogicalSealRef: accepted.handle.seal.previousSealRef, logicalSealSchema: "pocket.starling.candidate-seal.v1", logicalRootSchema: "pocket.starling.logical-root.v1", logicalObjectSchema: "pocket.starling.logical-object.v1", sequenceSchema: "pocket.starling.sequence-page.v2", placementGeneration: "pocket.starling.placement-relation.v1" }) }), base = await c.PocketStarlingLogicalEditShadow.createBase({ acceptedSealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), syncedPocketId: pocket, semanticAuthority: bundle.semanticAuthority, semanticBaseProof: semantic.semanticBaseProof });
  const root = JSON.parse(current.stager.store.get(current.seal.sealObject.rootRef)); current.stager.store.set(root.placementRef, "{}"); const equal = await c.PocketStarlingLogicalEditShadow.editPayload(base.base, "n", { label: "N", value: 1 }); assert.equal(equal.ok, false); assert.notEqual(equal.reason, "no-change"); assert.equal(equal.changed, undefined); assert.equal(equal.candidate, undefined); assert.equal(equal.newLogicalRefs, undefined);
});

test("P132l unauthenticated byte staging cannot manufacture semantic initial authority", async () => {
  const c = runtime(), pocket = "p132l-invalid", current = stage(c), wrapping = await c.PocketSyncCrypto.generateDeviceWrappingKey(), bundle = await c.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "d", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: wrapping }], { semanticAuthority: true }), physical = await c.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context: { syncedPocketId: pocket } });
  assert.ok(physical.sealStorageRef); const root = JSON.parse(current.stager.store.get(current.seal.sealObject.rootRef)); current.stager.store.set(root.placementRef, "{}");
  const audit = c.PocketStarlingObjectSealShadow.auditCandidateSeal(current.seal.sealRef, ref => current.stager.store.get(ref)); assert.equal(audit.ok, false); assert.equal(c.PocketStarlingObjectSealShadow.semanticAuditProvenance(audit), null); assert.equal((await c.PocketStarlingSemanticAuthorityShadow.issueInitial({ authority: bundle.semanticAuthority, auditProof: { ...audit } })).ok, false);
});

test("P132l fresh RemoteOpen reaches semantic verification after valid physical authentication without auditing", async () => {
  const c = runtime(), pocket = "p132l-remote", current = stage(c), context = { syncedPocketId: pocket }, wrapping = await c.PocketSyncCrypto.generateDeviceWrappingKey(), bundle = await c.PocketSyncCrypto.createMasterKeyBundle([{ context: { syncedPocketId: pocket, envelopeId: "d", envelopeKind: "device", envelopeVersion: 1 }, wrappingKey: wrapping }], { semanticAuthority: true }), audit = c.PocketStarlingObjectSealShadow.auditCandidateSeal(current.seal.sealRef, ref => current.stager.store.get(ref)), issued = await c.PocketStarlingSemanticAuthorityShadow.issueInitial({ authority: bundle.semanticAuthority, auditProof: c.PocketStarlingObjectSealShadow.semanticAuditProvenance(audit) }), staged = await c.PocketStarlingStorageShadow.stageCandidate({ sealRef: current.seal.sealRef, resolveLogical: ref => current.stager.store.get(ref), masterKey: bundle.masterKey, context, semanticAuthority: bundle.semanticAuthority, semanticValidityProof: issued.proof }), records = new Map(staged.newRecords.map(entry => [entry.storageRef, entry.record])), original = staged.newRecords.find(entry => entry.storageRef === staged.sealStorageRef), bytes = await c.PocketStarlingCryptoShadow.openObject(original.record, original.storageRef, bundle.masterKey, context), capsule = JSON.parse(bytes);
  async function open(record, expected) { const sealed = await c.PocketStarlingCryptoShadow.sealObject(JSON.stringify(record), bundle.masterKey, context), remote = new Map(records); remote.delete(original.storageRef); remote.set(sealed.ref, sealed.record); const opener = c.PocketStarlingRemoteOpenShadow.createRemoteOpener({ objectHeadService: { async readShadowHead() { return { head: { schema: "pocket.starling.head.v1", revision: 1, sealRef: sealed.ref } }; }, async getOpaqueObject({ storageRef }) { return { present: remote.has(storageRef), record: remote.get(storageRef) || null }; } }, operationIdFactory: (kind, index) => `${kind}-${index}` }); await assert.rejects(opener.openRemote({ masterKey: bundle.masterKey, context, semanticAuthority: bundle.semanticAuthority }), error => error.code === expected); }
  const { semanticValidity: _legacyAttestation, ...legacyCapsule } = capsule; await open({ ...legacyCapsule, schema: "pocket.starling.storage-capsule.v1" }, "semantic-validity-missing");
  for (const changed of [{ ...capsule, semanticValidity: { ...capsule.semanticValidity, tag: `${capsule.semanticValidity.tag.slice(0, -1)}${capsule.semanticValidity.tag.endsWith("A") ? "B" : "A"}` } }, ...["logicalSealRef","logicalRootRef","previousLogicalSealRef","logicalSealSchema","logicalRootSchema","logicalObjectSchema","sequenceSchema","placementGeneration","schema","algorithm"].map(field=>({ ...capsule, semanticValidity: { ...capsule.semanticValidity, [field]: field === "logicalSealRef" || field === "previousLogicalSealRef" ? "proof-ref:v1:candidate-seal:wrong" : field === "logicalRootRef" ? "proof-ref:v1:logical-root:wrong" : "wrong" } }))]) await open(changed, "semantic-validity-invalid");
  c.PocketStarlingObjectSealShadow = Object.freeze({ ...c.PocketStarlingObjectSealShadow, auditCandidateSeal() { throw new Error("unexpected whole audit"); } }); const remoteRoutes = [], opener = c.PocketStarlingRemoteOpenShadow.createRemoteOpener({ objectHeadService: { async readShadowHead() { remoteRoutes.push("readShadowHead"); return { head: { schema: "pocket.starling.head.v1", revision: 1, sealRef: staged.sealStorageRef } }; }, async getOpaqueObject({ storageRef }) { remoteRoutes.push("getOpaqueObject"); return { present: records.has(storageRef), record: records.get(storageRef) }; } }, operationIdFactory: (kind, index) => `${kind}-${index}` }), opened = await opener.openRemote({ masterKey: bundle.masterKey, context, semanticAuthority: bundle.semanticAuthority }); assert.equal(opened.outcome, "opened"); assert.deepEqual(remoteRoutes, ["readShadowHead", "getOpaqueObject", "getOpaqueObject"]); assert.ok(opened.session.semanticBaseProof); assert.equal(Object.isFrozen(opened.session.semanticBaseProof), true); assert.deepEqual(Object.getOwnPropertyNames(opened.session.semanticBaseProof), []);
});
