"use strict";

const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), vm = require("node:vm"), { webcrypto } = require("node:crypto"), { semanticBase } = require("./helpers/starling-semantic-test.js");
const ROOT = path.resolve(__dirname, ".."), MODULE = "js/pocket-starling-logical-edit-shadow.js", SCRIPTS = ["js/pocket-state.js", "js/pocket-data.js", "js/pocket-outline-persistence-policy.js", "js/pocket-editor-metadata.js", "js/pocket-pe-import-preserve.js", "js/pocket-storage.js", "js/pocket-import.js", "js/pocket-starling-shadow.js", "js/pocket-starling-sequence-shadow.js", "js/pocket-starling-placement-shadow.js", "js/pocket-starling-bridge-shadow.js", "js/pocket-starling-root-shadow.js", "js/pocket-starling-object-seal-shadow.js", "js/pocket-sync-crypto.js", MODULE, "js/pocket-starling-semantic-authority-shadow.js"];
const plain = (value) => JSON.parse(JSON.stringify(value));

function runtime() {
  const c = { crypto: webcrypto, TextEncoder, TextDecoder, Uint8Array, ArrayBuffer, URL, Date, Math, JSON, Map, Set, WeakMap, WeakSet, Object, Array, String, Number, Boolean, Promise, Error, btoa: (value) => Buffer.from(value, "binary").toString("base64"), atob: (value) => Buffer.from(value, "base64").toString("binary"), console: { log() {}, info() {}, warn() {}, error() {} }, localStorage: { getItem() {}, setItem() {}, removeItem() {} }, document: { body: { classList: { add() {}, remove() {}, toggle() {} } }, getElementById() {}, addEventListener() {} }, navigator: { clipboard: {} }, location: { href: "https://p143.test" }, indexedDB: null, open() {}, close() {}, setTimeout, clearTimeout, requestAnimationFrame() { return 1; }, cancelAnimationFrame() {} };
  c.window = c; c.globalThis = c; vm.createContext(c);
  for (const file of SCRIPTS) vm.runInContext(fs.readFileSync(path.join(ROOT, file), "utf8"), c, { filename: file });
  return c;
}

function graph(descendants = 2) {
  const nodes = [{ id: "source", parentId: "root", order: 0, label: "Source" }, { id: "destination", parentId: "root", order: 1, label: "Destination" }, { id: "unrelated", parentId: "root", order: 2, label: "Unrelated" }, { id: "first", parentId: "source", order: 0, label: "First" }, { id: "branch", parentId: "source", order: 1, label: "Branch" }, { id: "last", parentId: "source", order: 2, label: "Last" }, { id: "destination-child", parentId: "destination", order: 0, label: "Destination child" }, { id: "unrelated-child", parentId: "unrelated", order: 0, label: "Unrelated child" }, { id: "retained-old", parentId: "root", order: 3, label: "Retained" }, { id: "retained-child", parentId: "retained-old", order: 0, label: "Retained child" }, ...Array.from({ length: descendants }, (_, index) => ({ id: `d${String(index).padStart(4, "0")}`, parentId: index ? `d${String(index - 1).padStart(4, "0")}` : "branch", order: 0, label: `D${index}` }))], parents = Object.fromEntries(nodes.map((node) => [node.id, node.parentId])), children = { root: ["source", "destination", "unrelated"], source: ["first", "branch", "last"], destination: ["destination-child"], unrelated: ["unrelated-child"], "": ["retained-old"], "retained-old": ["retained-child"] };
  parents["retained-old"] = ""; if (descendants) { children.branch = ["d0000"]; for (let index = 0; index < descendants - 1; index += 1) children[`d${String(index).padStart(4, "0")}`] = [`d${String(index + 1).padStart(4, "0")}`]; }
  return { nodes, relation: { nodeIds: nodes.map((node) => node.id), parents, children } };
}

function stage(c, descendants = 2) {
  const input = graph(descendants), encoded = c.PocketStarlingBridgeShadow.encode({ schema: "portal.mtt.web.v1", writtenAt: "2026-09-02T00:00:00.000Z", nodes: input.nodes, tombstones: [], rootExtras: {}, dataExtras: {} }, { capacity: 4 }), base = encoded.ok && c.PocketStarlingRootShadow.build(encoded.bridge), structural = c.PocketStarlingPlacementShadow.build(input.relation, { capacity: 4 });
  assert.equal(encoded.ok && base.ok && structural.ok, true); const witness = c.PocketStarlingRootShadow.diagnosticRootFor({ capacity: base.state.capacity, content: base.state.content, placements: structural.model.placements, children: structural.model.children, preservation: base.state.preservation }); assert.equal(witness.ok, true);
  const stager = c.PocketStarlingObjectSealShadow.createStager(), staged = c.PocketStarlingObjectSealShadow.stageCandidate(stager, { schema: c.PocketStarlingRootShadow.SCHEMA, capacity: base.state.capacity, content: base.state.content, structural: structural.model, preservation: base.state.preservation, root: witness.root }, { previousSealRef: null }); assert.equal(staged.ok, true, JSON.stringify(staged)); return { stager, stage: staged.stage };
}

async function open(c, staged, id = "p143", resolver = null) { const resolveLogical = resolver || ((ref) => staged.stager.store.get(ref)), semantic = await semanticBase(c, { acceptedSealRef: staged.stage.sealRef, resolveLogical, syncedPocketId: id }), result = await c.PocketStarlingLogicalEditShadow.createBase({ acceptedSealRef: staged.stage.sealRef, resolveLogical, ...semantic }); assert.equal(result.ok, true, JSON.stringify(result)); return { ...result, ...semantic, id }; }
function resolve(staged, candidate) { return (ref) => candidate.resolveLogical(ref) || staged.stager.store.get(ref); }
function objectAt(resolveLogical, ref) { const bytes = resolveLogical(ref); assert.equal(typeof bytes, "string", ref); return JSON.parse(bytes); }
function trieValue(resolveLogical, rootRef, key) { let object = objectAt(resolveLogical, rootRef); for (const character of key) { const edge = object.children.find((item) => item.key === character); assert.ok(edge, key); object = objectAt(resolveLogical, edge.ref); } assert.equal(object.hasValue, true, key); return object.valueRef; }
function directRefs(object) { if (object.kind === "candidate-seal") return [object.rootRef, object.previousSealRef].filter(Boolean); if (object.kind === "pocket-root") return [object.contentRef, object.placementRef, object.childrenRef, object.preservationRef]; if (["content-trie", "placement-trie", "children-trie"].includes(object.kind)) return [...object.children.map((edge) => edge.ref), ...(object.hasValue ? [object.valueRef] : [])]; return object.kind === "sequence-branch" ? object.childRefs : []; }
function ownedReachable(staged, candidate) { const seen = new Set(), pending = [candidate.sealRef], owned = new Set(candidate.newLogicalRefs), read = resolve(staged, candidate); while (pending.length) { const ref = pending.pop(); if (seen.has(ref)) continue; seen.add(ref); for (const child of directRefs(objectAt(read, ref))) pending.push(child); } return new Set([...seen].filter((ref) => owned.has(ref))); }
function projection(marker) { return { source: { schema: "portal.mtt.web.v1", writtenAt: "2026-09-02T01:02:03.000Z" }, tombstones: [{ id: `gone-${marker}`, retained: { marker } }], rootExtras: { marker, nested: { stable: true } }, dataExtras: { marker: `data-${marker}`, nested: [marker] } }; }
function fail(result, reason, operationIndex = null) { assert.equal(result.ok, false, JSON.stringify(result)); assert.equal(result.reason, reason, JSON.stringify(result)); assert.deepEqual(Object.keys(result).sort(), (operationIndex === null ? ["ok", "reason"] : ["ok", "operationIndex", "reason"]).sort()); if (operationIndex !== null) assert.equal(result.operationIndex, operationIndex); assert.equal(Object.isFrozen(result), true); for (const key of ["candidate", "newLogicalRefs", "rootRef", "sealRef", "binding", "proof"]) assert.equal(key in result, false, key); }
function allOps() { return [{ type: "payload", input: { nodeId: "first", payload: { label: "First edited" } } }, { type: "move", input: { nodeId: "branch", fromIndex: 1, newParentId: "destination", toIndex: 1 } }, { type: "insert", input: { nodeId: "P", parentId: "root", toIndex: 1, payload: { label: "P" } } }, { type: "insert", input: { nodeId: "C", parentId: "P", toIndex: 0, payload: { label: "C" } } }, { type: "payload", input: { nodeId: "C", payload: { label: "C edited" } } }, { type: "move", input: { nodeId: "C", fromIndex: 0, newParentId: "destination", toIndex: 2 } }, { type: "reorder", input: { nodeId: "C", fromIndex: 2, toIndex: 1 } }, { type: "delete", input: { nodeId: "C", fromIndex: 1 } }, { type: "restore", input: { nodeId: "C", fromIndex: 1, newParentId: "P", toIndex: 0 } }, { type: "reorder", input: { nodeId: "P", fromIndex: 1, toIndex: 0 } }]; }

test("P143 projects owner preservation after a bounded authenticated no-op", async () => {
  const c = runtime(), staged = stage(c, 2000), api = c.PocketStarlingLogicalEditShadow, baseRoot = staged.stage.rootObject, baseRead = (ref) => staged.stager.store.get(ref), deep = { content: trieValue(baseRead, baseRoot.contentRef, "d1000"), placement: trieValue(baseRead, baseRoot.placementRef, "d1000"), children: trieValue(baseRead, baseRoot.childrenRef, "d1000") }, calls = [], measurement = { active: false }, opened = await open(c, staged, "p143-projection", (ref) => { if (measurement.active) calls.push(ref); if (measurement.active && Object.values(deep).includes(ref)) throw new Error(`deep read ${ref}`); return baseRead(ref); }), before = api.diagnostics(opened.base), supplied = projection("only"); measurement.active = true; const result = await api.compose(opened.base, [], supplied); measurement.active = false;
  assert.deepEqual(Object.keys(api).sort(), ["compose", "createBase", "deleteBranch", "diagnostics", "editPayload", "insert", "move", "reorder", "restoreBranch", "semanticTransitionBinding"].sort()); assert.equal(api.compose.length, 3); assert.deepEqual(Object.keys(result).sort(), ["candidate", "changed", "ok"]); assert.equal(result.ok && result.changed && Object.isFrozen(result) && Object.isFrozen(result.candidate), true); assert.deepEqual(Object.keys(result.candidate).sort(), ["diagnostics", "newLogicalRefs", "resolveLogical", "rootRef", "sealRef"]); const root = objectAt(resolve(staged, result.candidate), result.candidate.rootRef), seal = objectAt(resolve(staged, result.candidate), result.candidate.sealRef), preserved = objectAt(resolve(staged, result.candidate), root.preservationRef);
  assert.equal(root.contentRef, baseRoot.contentRef); assert.equal(root.placementRef, baseRoot.placementRef); assert.equal(root.childrenRef, baseRoot.childrenRef); assert.notEqual(root.preservationRef, baseRoot.preservationRef); assert.deepEqual(plain(preserved), { schema: c.PocketStarlingObjectSealShadow.OBJECT_SCHEMA, kind: "preservation", value: supplied }); assert.equal(seal.previousSealRef, staged.stage.sealRef); assert.equal(result.candidate.newLogicalRefs.length, 3); assert.deepEqual([...ownedReachable(staged, result.candidate)].sort(), [...result.candidate.newLogicalRefs].sort()); assert.equal(result.candidate.diagnostics.logicalFetches - before.logicalFetches <= 1, true); assert.equal(calls.some((ref) => Object.values(deep).includes(ref)), false); assert.equal(c.PocketStarlingObjectSealShadow.auditCandidateSeal(result.candidate.sealRef, resolve(staged, result.candidate)).ok, true);
  const semantic = c.PocketStarlingSemanticAuthorityShadow, issued = await semantic.issueSuccessor({ authority: opened.semanticAuthority, semanticBaseProof: opened.semanticBaseProof, candidate: result.candidate }), binding = api.semanticTransitionBinding(result.candidate, opened.semanticAuthority, opened.semanticBaseProof); assert.equal(issued.ok, true); assert.ok(binding); assert.equal((await semantic.issueSuccessor({ authority: opened.semanticAuthority, semanticBaseProof: opened.semanticBaseProof, candidate: { ...result.candidate } })).ok, false);
});

test("P143 keeps identical owner projection as the exact no-change surface", async () => {
  const c = runtime(), staged = stage(c), opened = await open(c, staged), api = c.PocketStarlingLogicalEditShadow, current = plain(objectAt((ref) => staged.stager.store.get(ref), staged.stage.rootObject.preservationRef).value), result = await api.compose(opened.base, [], current);
  assert.deepEqual(plain(result), { ok: true, changed: false, reason: "no-change" }); assert.equal(Object.isFrozen(result), true); assert.equal("candidate" in result, false);
});

test("P143 combines all P139 logical operations with one final preservation projection", async () => {
  const c = runtime(), staged = stage(c), api = c.PocketStarlingLogicalEditShadow, ordinary = await open(c, staged, "p143-ordinary"), projected = await open(c, staged, "p143-projected"), without = await api.compose(ordinary.base, allOps()), supplied = projection("combined"), withProjection = await api.compose(projected.base, allOps(), supplied);
  assert.equal(without.ok && withProjection.ok && without.changed && withProjection.changed, true); const ordinaryRoot = objectAt(resolve(staged, without.candidate), without.candidate.rootRef), projectedRoot = objectAt(resolve(staged, withProjection.candidate), withProjection.candidate.rootRef); for (const key of ["contentRef", "placementRef", "childrenRef"]) assert.equal(projectedRoot[key], ordinaryRoot[key], key); assert.notEqual(projectedRoot.preservationRef, ordinaryRoot.preservationRef); assert.deepEqual(plain(objectAt(resolve(staged, withProjection.candidate), projectedRoot.preservationRef).value), supplied); assert.equal(objectAt(resolve(staged, withProjection.candidate), withProjection.candidate.sealRef).previousSealRef, staged.stage.sealRef); assert.equal(withProjection.candidate.resolveLogical(without.candidate.rootRef), undefined); assert.equal(withProjection.candidate.resolveLogical(without.candidate.sealRef), undefined); assert.deepEqual([...ownedReachable(staged, withProjection.candidate)].sort(), [...withProjection.candidate.newLogicalRefs].sort()); assert.equal((await api.editPayload(projected.base, "unrelated", { label: "base reusable" })).ok, true);
});

test("P143 keeps failure priority and logical base isolation", async () => {
  const c = runtime(), staged = stage(c), opened = await open(c, staged), api = c.PocketStarlingLogicalEditShadow, bad = { source: { schema: "x", writtenAt: "y" }, tombstones: [], rootExtras: { nonfinite: Infinity }, dataExtras: {} };
  fail(await api.compose(opened.base, [{ type: "missing", input: {} }], bad), "invalid-compose-input"); fail(await api.compose(opened.base, [], bad), "invalid-owner-projection"); fail(await api.compose(opened.base, [{ type: "payload", input: { nodeId: "first", payload: { label: "changed" } } }, { type: "delete", input: { nodeId: "retained-old", fromIndex: 0 } }], projection("failure")), "retained-node-not-current", 1); assert.equal((await api.editPayload(opened.base, "first", { label: "reusable" })).ok, true);
});

test("P143 snapshots a detached projection before the first logical await", async () => {
  const c = runtime(), staged = stage(c), api = c.PocketStarlingLogicalEditShadow, baseRoot = staged.stage.rootObject, gate = Promise.withResolvers(), started = Promise.withResolvers(); let active = false, held = true; const opened = await open(c, staged, "p143-snapshot", (ref) => { if (active && held && ref === baseRoot.contentRef) { held = false; started.resolve(); return gate.promise; } return staged.stager.store.get(ref); }), supplied = projection("before"), expected = plain(supplied); active = true; const pending = api.compose(opened.base, [{ type: "payload", input: { nodeId: "first", payload: { label: "changed" } } }], supplied);
  await started.promise; supplied.source.writtenAt = "caller-redirection"; supplied.tombstones[0].retained.marker = "caller-redirection"; supplied.rootExtras.nested.stable = false; supplied.dataExtras.nested.push("caller-redirection"); gate.resolve(staged.stager.store.get(baseRoot.contentRef)); const result = await pending, root = objectAt(resolve(staged, result.candidate), result.candidate.rootRef), preserved = objectAt(resolve(staged, result.candidate), root.preservationRef); assert.equal(result.ok && result.changed, true); assert.deepEqual(plain(preserved.value), expected);
});
