"use strict";

const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path"), vm = require("node:vm"), { webcrypto } = require("node:crypto"), { semanticBase } = require("./helpers/starling-semantic-test.js");
const ROOT = path.resolve(__dirname, ".."), SHADOW = "js/pocket-starling-owner-working-set-shadow.js", HISTORY = "js/pocket-history-status.js", DATA = "js/pocket-data.js", DETAILS = "js/pocket-editor-copy.js";
const LOGICAL = ["js/pocket-state.js", "js/pocket-data.js", "js/pocket-outline-persistence-policy.js", "js/pocket-editor-metadata.js", "js/pocket-pe-import-preserve.js", "js/pocket-storage.js", "js/pocket-import.js", "js/pocket-starling-shadow.js", "js/pocket-starling-sequence-shadow.js", "js/pocket-starling-placement-shadow.js", "js/pocket-starling-bridge-shadow.js", "js/pocket-starling-root-shadow.js", "js/pocket-starling-object-seal-shadow.js", "js/pocket-sync-crypto.js", "js/pocket-starling-logical-edit-shadow.js", "js/pocket-starling-semantic-authority-shadow.js"];
function source(file) { return fs.readFileSync(path.join(ROOT, file), "utf8"); }
function plain(value) { return value === undefined ? undefined : JSON.parse(JSON.stringify(value)); }
function node(id, parentId = "root", order = 1001, extra = {}) { return { id, parentId, order, label: id, updatedAt: "2026-09-02T00:00:00.000Z", ...extra }; }

function runtime(nodes) {
  class HTMLElement { focus() {} select() {} }
  class HTMLInputElement extends HTMLElement { constructor(value = "") { super(); this.value = value; this.checked = false; } }
  class HTMLTextAreaElement extends HTMLElement { constructor(value = "") { super(); this.value = value; } }
  const storage = new Map(), overlay = new HTMLElement(); overlay.hidden = false;
  const context = { Object, Array, String, Number, Boolean, Map, Set, Error, Function, Reflect, JSON, Date, Promise, structuredClone, HTMLElement, HTMLInputElement, HTMLTextAreaElement,
    state: { nodes: plain(nodes), tombstones: [], rootExtras: {}, dataExtras: {}, collapsed: new Set(), selectedId: "task", focusRootId: "", moveMode: false, inlineEdit: { id: "", isNew: false }, detailsEdit: { id: "", draftOpRecorded: false, draftOperationSequence: 0, draftHadCoveredSave: false }, ops: [], operationHighWater: 0, operationDocumentAnchor: null, activeSaveOperationCeiling: 0, documentBaseline: null, source: { schema: "portal.export.v1", fileName: "p159.json", writtenAt: "" } },
    el: { detailOverlay: overlay, detailEditorLabel: new HTMLInputElement(), detailEditorBody: new HTMLTextAreaElement(), detailEditorUrgent: new HTMLInputElement(), detailEditorCopyContext: new HTMLInputElement() }, document: { readyState: "complete", addEventListener() {}, getElementById() { return null; } }, localStorage: { getItem(key) { return storage.get(String(key)) || null; }, setItem(key, value) { storage.set(String(key), String(value)); } }, DEVICE_CHANGE_SEQUENCE_KEY: "p159.sequence",
    makeId() { return "completed-bucket"; }, maxSiblingOrder(parentId) { return Math.max(1000, ...context.state.nodes.filter((entry) => (entry.parentId || "root") === (parentId || "root")).map((entry) => Number(entry.order) || 0)); }, nodeMap() { return new Map(context.state.nodes.map((entry) => [entry.id, entry])); }, getPath(id) { return id; },
    clearInlineEditState() {}, refocusTreeNavigation() {}, refreshMeta() {}, renderTree() {}, persistPipSnapshot() {}, flashTouchedRow() {}, expandPathToNode() {}, requestAnimationFrame(callback) { callback?.(); return 1; }, setStatus() {}, requirePocketFileForChanges() { return true; }, saveLocalSafetySnapshot() { return true; }, clearLocalSafetySnapshot() {}, resetPocketOperationAnchor() { return true; }, PocketDetailDirtyState: { refresh() {} },
    PocketDeviceChanges: { cloneJsonCompatible(value) { try { return { ok: true, value: plain(value) }; } catch { return { ok: false }; } }, coerceDocument(value) { return { ok: true, document: plain({ nodes: value.nodes || [], tombstones: value.tombstones || [], rootExtras: value.rootExtras || {}, dataExtras: value.dataExtras || {} }) }; }, describeDocumentTransition() { return { ok: true, records: [] }; } },
  };
  context.sortNodesForParent = (parentId) => context.state.nodes.filter((entry) => (entry.parentId || "root") === (parentId || "root")).sort((left, right) => context.compareSiblingOrder(left, right, parentId));
  context.window = context; context.globalThis = context; vm.createContext(context); for (const file of [SHADOW, HISTORY, DATA, DETAILS]) vm.runInContext(source(file), context, { filename: file });
  context.refreshMeta = context.renderTree = context.persistPipSnapshot = context.refocusTreeNavigation = context.flashTouchedRow = context.expandPathToNode = () => {}; return context;
}

function openAndComplete(context, id = "task", details = "Finish this #completed") { const current = context.nodeMap().get(id); context.state.detailsEdit = { id, originalLabel: current.label, originalDetails: current.details || "", originalUrgent: !!current.urgent, originalCopyContext: !!current.copyContext, draftOpRecorded: false, draftOperationSequence: 0, draftHadCoveredSave: false }; context.el.detailEditorLabel.value = current.label; context.el.detailEditorBody.value = details; context.saveDetailsEditor(); return plain(context.state.ops.at(-1)); }
function captured(context, sequence) { const frozen = context.freezePocketStarlingOwnerWorkingSetThrough(sequence); return frozen ? plain(frozen.operations) : null; }

test("P159 records a created Completed bucket, task Payload and branch-root Move atomically under details_edit", () => {
  const context = runtime([node("before", "root", 810), node("task", "root", 920, { details: "Old" }), node("after", "root", 1030), node("child", "task", 3)]), operation = openAndComplete(context), bucket = context.nodeMap().get("completed-bucket"), task = context.nodeMap().get("task"), operations = captured(context, operation.seq);
  assert.equal(operation.type, "details_edit"); assert.equal(context.state.ops.filter((entry) => entry.type === "details_edit").length, 1); assert.ok(bucket); assert.equal(task.parentId, bucket.id); assert.equal(context.nodeMap().get("child").parentId, "task");
  assert.deepEqual(operations.map((entry) => entry.type), ["insert", "payload", "move"]); assert.deepEqual(operations[0].input.parentId, "root"); assert.equal(operations[0].input.toIndex, 3); assert.equal(operations[1].input.nodeId, "task"); assert.deepEqual(operations[2].input, { nodeId: "task", fromIndex: 1, newParentId: bucket.id, toIndex: 0 }); assert.equal(operations.some((entry) => entry.input?.nodeId === "child"), false);
  assert.equal(operations[0].input.payload.system.bucketType, "completed"); assert.equal(operations[1].input.payload.status.completed, true); assert.equal(operations[1].input.payload.details, "Finish this");
});

test("P159 refreshes an existing Completed bucket before the completed task Payload and Move", () => {
  const bucket = node("bucket", "root", 99, { label: "Old", source: "old", system: { kind: "bucket", bucketType: "completed", managed: true, pinnedLast: true } }), context = runtime([node("task", "root", 11), node("other", "root", 60), bucket, node("old-completed", "bucket", 1)]), operation = openAndComplete(context), operations = captured(context, operation.seq);
  assert.deepEqual(operations.map((entry) => entry.type), ["payload", "payload", "move"]); assert.equal(operations[0].input.nodeId, "bucket"); assert.equal(operations[1].input.nodeId, "task"); assert.deepEqual(operations[2].input, { nodeId: "task", fromIndex: 0, newParentId: "bucket", toIndex: 1 }); assert.equal(operations[0].input.payload.updatedAt, context.nodeMap().get("bucket").updatedAt);
});

test("P159 composes the captured created-bucket completion through genuine P139 without descendant operations", async () => {
  const before = [node("before", "root", 810), node("task", "root", 920, { details: "Old" }), node("after", "root", 1030), node("child", "task", 3), node("grandchild", "child", 4)], context = runtime(before), operation = openAndComplete(context), relation = await composeCapturedThroughP139(before, captured(context, operation.seq));
  assert.deepEqual(relation.children.root, ["before", "after", "completed-bucket"]); assert.deepEqual(relation.children["completed-bucket"], ["task"]); assert.equal(relation.parents.child, "task"); assert.equal(relation.parents.grandchild, "child");
});

test("P159 composes a pending prior Insert with the later completion without cancellation", async () => {
  const before = [node("before", "root", 810), node("after", "root", 1030)], task = node("task", "root", 920), context = runtime([before[0], task, before[1]]), inserted = context.recordOp({ type: "add_below", id: "task" });
  assert.equal(context.capturePocketStarlingNodeInsert(inserted.seq, context.nodeMap().get("task"), "root", 1), true);
  const completed = openAndComplete(context), operations = captured(context, completed.seq), relation = await composeCapturedThroughP139(before, operations);
  assert.deepEqual(operations.map((entry) => entry.type), ["insert", "insert", "payload", "move"]); assert.equal(context.state.ops[0].type, "add_below"); assert.equal(context.state.ops[1].type, "details_edit"); assert.deepEqual(relation.children.root, ["before", "after", "completed-bucket"]); assert.deepEqual(relation.children["completed-bucket"], ["task"]);
});

test("P159 preserves ordinary details payload capture and leaves a moved completion silent if combined capture is unavailable", () => {
  const ordinary = runtime([node("task", "root", 10, { details: "Old" })]); ordinary.state.detailsEdit = { id: "task", originalLabel: "task", originalDetails: "Old", originalUrgent: false, originalCopyContext: false, draftOpRecorded: false, draftOperationSequence: 0, draftHadCoveredSave: false }; ordinary.el.detailEditorLabel.value = "task"; ordinary.el.detailEditorBody.value = "Updated"; ordinary.saveDetailsEditor(); const plainOperation = plain(ordinary.state.ops.at(-1)); assert.deepEqual(captured(ordinary, plainOperation.seq).map((entry) => entry.type), ["payload"]);
  const unavailable = runtime([node("task", "root", 10), node("after", "root", 20)]); unavailable.capturePocketStarlingCompletedMove = undefined; const operation = openAndComplete(unavailable); assert.equal(operation.type, "details_edit"); assert.deepEqual(captured(unavailable, operation.seq), []); assert.equal(unavailable.nodeMap().get("task").status.completed, true);
  const ordering = runtime([node("task", "root", 10), node("after", "root", 20)]); ordering.sortNodesForParent = () => { throw new Error("ordering unavailable"); }; const orderingOperation = openAndComplete(ordering); assert.equal(orderingOperation.type, "details_edit"); assert.deepEqual(captured(ordering, orderingOperation.seq), []); assert.equal(ordering.nodeMap().get("task").status.completed, true);
});

function logicalRuntime() { const context = { crypto: webcrypto, TextEncoder, TextDecoder, Uint8Array, ArrayBuffer, URL, Date, Math, JSON, Map, Set, WeakMap, WeakSet, Object, Array, String, Number, Boolean, Promise, Error, btoa(value) { return Buffer.from(value, "binary").toString("base64"); }, atob(value) { return Buffer.from(value, "base64").toString("binary"); }, console: { log() {}, info() {}, warn() {}, error() {} }, localStorage: { getItem() {}, setItem() {}, removeItem() {} }, document: { body: { classList: { add() {}, remove() {}, toggle() {} } }, getElementById() {}, addEventListener() {} }, navigator: { clipboard: {} }, location: { href: "https://example.test" }, indexedDB: null, open() {}, close() {}, setTimeout() { return 1; }, clearTimeout() {}, requestAnimationFrame() { return 1; }, cancelAnimationFrame() {} }; context.window = context; context.globalThis = context; vm.createContext(context); for (const file of LOGICAL) vm.runInContext(source(file), context, { filename: file }); return context; }

async function composeCapturedThroughP139(nodes, operations) {
  const context = logicalRuntime(), byId = new Map(nodes.map((entry) => [entry.id, entry])), children = {};
  for (const entry of nodes) children[entry.id] = []; for (const entry of nodes) { const parentId = entry.parentId || "root"; if (!children[parentId]) children[parentId] = []; children[parentId].push(entry.id); } for (const ids of Object.values(children)) ids.sort((left, right) => (Number(byId.get(left)?.order) || 0) - (Number(byId.get(right)?.order) || 0));
  const relation = { nodeIds: nodes.map((entry) => entry.id), parents: Object.fromEntries(nodes.map((entry) => [entry.id, entry.parentId || "root"])), children }, encoded = context.PocketStarlingBridgeShadow.encode({ schema: "portal.mtt.web.v1", writtenAt: "2026-09-02T00:00:00.000Z", nodes, tombstones: [], rootExtras: {}, dataExtras: {} }, { capacity: 4 }), root = context.PocketStarlingRootShadow.build(encoded.bridge), structural = context.PocketStarlingPlacementShadow.build(relation, { capacity: 4 }), witness = context.PocketStarlingRootShadow.diagnosticRootFor({ capacity: root.state.capacity, content: root.state.content, placements: structural.model.placements, children: structural.model.children, preservation: root.state.preservation }), stager = context.PocketStarlingObjectSealShadow.createStager(), staged = context.PocketStarlingObjectSealShadow.stageCandidate(stager, { schema: context.PocketStarlingRootShadow.SCHEMA, capacity: root.state.capacity, content: root.state.content, structural: structural.model, preservation: root.state.preservation, root: witness.root }, { previousSealRef: null }), resolveLogical = (ref) => stager.store.get(ref), semantic = await semanticBase(context, { acceptedSealRef: staged.stage.sealRef, resolveLogical, syncedPocketId: "p159" }), opened = await context.PocketStarlingLogicalEditShadow.createBase({ acceptedSealRef: staged.stage.sealRef, resolveLogical, ...semantic }), composed = await context.PocketStarlingLogicalEditShadow.compose(opened.base, operations), resolve = (ref) => composed.candidate.resolveLogical(ref) || resolveLogical(ref), audited = context.PocketStarlingObjectSealShadow.auditCandidateSeal(composed.candidate.sealRef, resolve), materialised = context.PocketStarlingPlacementShadow.materialise(audited.candidate.structural);
  assert.equal(encoded.ok && root.ok && structural.ok && witness.ok && staged.ok && opened.ok && composed.ok && audited.ok && materialised.ok, true); return plain(materialised.relation);
}

test("P159 remains limited to completion data, history, and Details capture seams", () => {
  const history = source(HISTORY), data = source(DATA), details = source(DETAILS); assert.match(history, /function capturePocketStarlingCompletedMove\(sequence, node, bucket, completion\)/); assert.match(data, /function moveNodeIntoCompletedSystemBucket\(nodeId\)/); assert.match(details, /capturePocketStarlingCompletedMove/);
  for (const program of [history, data, details]) assert.doesNotMatch(program, /LogicalEdit|RemoteEdit|RemoteSave|PocketOwnerSaveBoundary|compareAndSetShadowHead/);
});
