"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const ROOT = path.resolve(__dirname, "..");
const source = (file) => fs.readFileSync(path.join(ROOT, file), "utf8");
function ctx() { const c={TextEncoder,JSON,Object,Array,String,Number,Boolean,Math,Map,Set,Date,console:{log(){},info(){},warn(){},error(){}},normaliseDetails(v,m=4000){return String(v||"").replace(/\r/g,"").trim().slice(0,m);}}; c.window=c;c.globalThis=c;vm.createContext(c); vm.runInContext(source("js/pocket-outline-persistence-policy.js"),c); vm.runInContext(source("js/pocket-node-content.js"),c); vm.runInContext(source("js/pocket-editor-metadata.js"),c); return c; }
const v1=(rows)=>({schema:"pocket.nodeEditor.v1",mode:"outline",outline:rows});
const node=(overrides={})=>({id:"n",label:"Node",updatedAt:"2026-01-01T00:00:00.000Z",...overrides});

test("P198-01 details-only opening is the unified document",()=>{const c=ctx();assert.equal(c.PocketNodeContent.readNode(node({details:"hello\nworld"})).text,"hello\nworld");});
test("P198-02 v1 outline opens by array-order projection",()=>{const c=ctx();const view=c.PocketNodeContent.readNode(node({editor:v1([{id:"a",text:"A",depth:0},{id:"b",text:"B",depth:2}])}));assert.equal(view.text,"A\n    B");});
test("P198-03 exact duplicate legacy pair is not duplicated",()=>{const c=ctx();const editor=v1([{id:"a",text:"A",depth:0},{id:"b",text:"B",depth:1}]);assert.equal(c.PocketNodeContent.readNode(node({details:"A\n  B",editor})).text,"A\n  B");});
test("P198-04 distinct legacy pair is deterministic and lossless",()=>{const c=ctx();const editor=v1([{id:"a",text:"Outline",depth:0}]);assert.equal(c.PocketNodeContent.readNode(node({details:"Notes",editor})).text,"Notes\n\nOutline");});
test("P198-05 unknown editor stays read-only with readable details only",()=>{const c=ctx();const view=c.PocketNodeContent.readNode(node({details:"safe",editor:{schema:"future.v9",secret:"opaque"}}));assert.equal(view.readOnly,true);assert.equal(view.text,"safe");});
test("P198-06 v2 text is authoritative over details",()=>{const c=ctx();const view=c.PocketNodeContent.readNode(node({details:"old",editor:{schema:"pocket.nodeEditor.v2",text:"full\n  child"}}));assert.equal(view.text,"full\n  child");});
test("P198-07 generated first paint already contains details and v1 content",()=>{const c=ctx();const tc={...c,document:{}};tc.window=tc;vm.createContext(tc);vm.runInContext(source("js/pocket-node-popout-template.js"),tc);const h={htmlEscape:(x)=>String(x).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;"),contentAssetUrl:"/js/pocket-node-content.js",runtimeAssetUrl:"/js/pocket-node-popout-runtime.js"};const a=tc.PocketNodePopoutTemplate.render({title:"T",text:"hello",body:"hello"},h);const b=tc.PocketNodePopoutTemplate.render({title:"T",text:"Parent\n  Child",body:"Parent\n  Child"},h);assert.match(a,/>hello<\/div>/);assert.match(b,/>Parent<\/div>/);assert.match(b,/>Child<\/div>/);});
test("P198-08 canonical PE has one document surface and no Notes/Outline mode controls",()=>{const t=source("js/pocket-node-popout-template.js");assert.doesNotMatch(t,/textModeBtn|outlineModeBtn|>Notes<|>Outline</);assert.match(t,/aria-label="Document"/);});
test("P198-09 smart numbering continues positive integer marker",()=>{const c=ctx();assert.deepEqual(JSON.parse(JSON.stringify(c.PocketNodeContent.smartContinuation("9. item"))),{exitList:false,content:"10. "});});
test("P198-10 bullets continue and empty markers exit to prose",()=>{const c=ctx();assert.equal(c.PocketNodeContent.smartContinuation("- item").content,"- ");assert.equal(c.PocketNodeContent.smartContinuation("* ").exitList,true);assert.equal(c.PocketNodeContent.smartContinuation("1. ").content,"");});
test("P198-11 hierarchy is indentation-only and plain parent is a branch head",()=>{const c=ctx();const lines=c.PocketNodeContent.parseLines("plain parent\n  child\n- sibling\n  1. nested");assert.equal(c.PocketNodeContent.hasChildren(lines,0),true);assert.equal(c.PocketNodeContent.hasChildren(lines,2),true);assert.equal(c.PocketNodeContent.serialiseLines(lines),"plain parent\n  child\n- sibling\n  1. nested");});
test("P198-12 real details mutation prepares one v2 text truth plus bounded projection",()=>{const c=ctx();c.capturePocketEditorSourceIdentity=()=>({fileSessionId:1,sourceFileName:"x.json",sourcePipSession:false,sourceOwnerKind:"json",sourceVaultSessionId:""});c.getPath=()=>"Node";vm.runInContext(source("js/pocket-node-popout-model.js"),c);const n=node({details:"old"});const p=c.PocketNodePopoutModel.prepareSave(n,{title:"Node",text:"new\n  child"});assert.equal(p.contentChanged,true);assert.deepEqual(JSON.parse(JSON.stringify(p.editorMeta)),{schema:"pocket.nodeEditor.v2",text:"new\n  child"});assert.equal(p.nextDetails,"new\n  child");});
test("P198-13 v1-only and dual legacy genuine edits migrate losslessly to v2",()=>{const c=ctx();c.capturePocketEditorSourceIdentity=()=>({});c.getPath=()=>"";vm.runInContext(source("js/pocket-node-popout-model.js"),c);for(const n of [node({editor:v1([{id:"a",text:"A",depth:0}])}),node({details:"Notes",editor:v1([{id:"a",text:"A",depth:0}])})]){const before=c.PocketNodeContent.readNode(n).text;const p=c.PocketNodePopoutModel.prepareSave(n,{title:"Node",text:before+"!"});assert.equal(p.editorMeta.schema,"pocket.nodeEditor.v2");assert.equal(p.editorMeta.text,before+"!");}});
test("P198-14 unchanged/title-only save does not migrate raw v1",()=>{const c=ctx();c.capturePocketEditorSourceIdentity=()=>({});c.getPath=()=>"";vm.runInContext(source("js/pocket-node-popout-model.js"),c);const raw=v1([{id:"a",text:"A",depth:0,future:true}]);const n=node({details:"Notes",editor:raw});const open=c.PocketNodeContent.readNode(n).text;const p=c.PocketNodePopoutModel.prepareSave(n,{title:"Renamed",text:open});assert.equal(p.contentChanged,false);assert.equal(p.preserveRawEditor,true);assert.strictEqual(p.editorMeta,raw);});
test("P198-15 canonical envelope absorbs accepted v1 plus distinct legacy details and rejects oversize input",()=>{const c=ctx();assert.ok(c.PocketNodeContent.LIMITS.canonicalBytes>2000000+12000);const limit=c.PocketNodeContent.LIMITS.canonicalBytes;assert.equal(c.PocketNodeContent.validateText("x".repeat(limit)).ok,true);assert.equal(c.PocketNodeContent.validateText("x".repeat(limit+1)).ok,false);});
test("P198-16 source/revision/permission checks still precede mutation",()=>{const s=source("js/pocket-node-popout-editor.js");assert.match(s,/canModifyPocket/);assert.match(s,/validateSourceIdentity\(payload\)/);assert.match(s,/originalUpdatedAt !== currentUpdatedAt/);assert.match(s,/node\.label = prepared\.nextLabel/);});
test("P198-17 Save and Save & Close still share one durable save path and failed saves remain dirty",()=>{const s=source("js/pocket-node-popout-runtime.js");assert.match(s,/saveBtn\.addEventListener\([^\n]+save\(false\)/);assert.match(s,/saveCloseBtn\.addEventListener\([^\n]+save\(true\)/);assert.match(s,/setDirty\(true\)/);assert.match(s,/result\.ok && result\.exported/);});
test("P198-18 active in-page copy/search/recovery readers use PocketNodeContent",()=>{for(const f of ["js/pocket-editor-copy.js","js/pocket-render.js","js/pocket-vault-recovery-viewer.js"])assert.match(source(f),/PocketNodeContent/,f);});
test("P198-19 unknown editor remains opaque and apply path rejects it before mutation",()=>{const s=source("js/pocket-node-popout-editor.js");assert.ok(s.indexOf('currentEditor.kind === "unsupported-or-malformed"')<s.indexOf("node.label = prepared.nextLabel"));});
test("P198-20 release composition loads one content contract before metadata and PE surfaces",()=>{const index=source("index.html");const c=index.indexOf("js/pocket-node-content.js");assert.ok(c>index.indexOf("js/pocket-outline-persistence-policy.js"));assert.ok(c<index.indexOf("js/pocket-editor-metadata.js"));assert.ok(c<index.indexOf("js/pocket-node-popout-model.js"));});
test("P198-21 collapse is presentation-only in runtime source",()=>{const s=source("js/pocket-node-popout-runtime.js");const start=s.indexOf("function toggleBranch(index)");const end=s.indexOf("function indentBranch",start);const body=s.slice(start,end);assert.doesNotMatch(body,/markMutation|setDirty|editGeneration/);});
test("P198-22 canonical text has no persisted mode/outline shadow",()=>{const c=ctx();const p=c.PocketNodeContent.prepareCanonical("A\n  B");assert.deepEqual(Object.keys(p.editor).sort(),["schema","text"]);assert.equal(p.editor.schema,"pocket.nodeEditor.v2");});


test("P198a-23 active body parser preserves canonical content beyond legacy 4000-char projection",()=>{const c=ctx();const long="A".repeat(5200)+"\n  child";const parsed=c.PocketNodeContent.parseEditorBody(long);assert.equal(parsed.text,long);assert.equal(parsed.text.length>4000,true);const prepared=c.PocketNodeContent.prepareCanonical(parsed.text);assert.equal(prepared.editor.text,long);assert.equal(prepared.details.length<=4000,true);});
test("P198a-24 subtree indent/outdent transforms the whole plain-text branch exactly",()=>{const c=ctx();const start=c.PocketNodeContent.parseLines("A\nB\n  B child\nC");const ind=c.PocketNodeContent.indentSubtree(start,1,1);assert.equal(ind.ok,true);assert.equal(c.PocketNodeContent.serialiseLines(ind.lines),"A\n  B\n    B child\nC");const out=c.PocketNodeContent.indentSubtree(ind.lines,1,-1);assert.equal(out.ok,true);assert.equal(c.PocketNodeContent.serialiseLines(out.lines),"A\nB\n  B child\nC");});
test("P198a-25 subtree move keeps descendants attached and canonical text exact",()=>{const c=ctx();const start=c.PocketNodeContent.parseLines("A\n  A child\nB\n  B child\nC");const down=c.PocketNodeContent.moveSubtree(start,0,"down");assert.equal(down.ok,true);assert.equal(c.PocketNodeContent.serialiseLines(down.lines),"B\n  B child\nA\n  A child\nC");const up=c.PocketNodeContent.moveSubtree(down.lines,2,"up");assert.equal(up.ok,true);assert.equal(c.PocketNodeContent.serialiseLines(up.lines),"A\n  A child\nB\n  B child\nC");});
test("P198a-26 plain and marker branches collapse exact descendant ranges without changing canonical text",()=>{const c=ctx();const lines=c.PocketNodeContent.parseLines("Plain\n  child\n    grandchild\n- marker\n  marker child\nTail");const canonical=c.PocketNodeContent.serialiseLines(lines);assert.equal(c.PocketNodeContent.hasChildren(lines,0),true);assert.equal(c.PocketNodeContent.hasChildren(lines,3),true);assert.deepEqual(Array.from(c.PocketNodeContent.visibleIndexes(lines,new Set([lines[0].id]))),[0,3,4,5]);assert.deepEqual(Array.from(c.PocketNodeContent.visibleIndexes(lines,new Set([lines[3].id]))),[0,1,2,3,5]);assert.equal(c.PocketNodeContent.serialiseLines(lines),canonical);});
test("P198a-27 active in-page body seam no longer routes canonical content through the 4000-char Notes parser",()=>{const s=source("js/pocket-editor-copy.js");assert.match(s,/parsePocketNodeContentEditorBody/);assert.match(s,/el\.detailEditorBody\.value = contentView\.text/);const start=s.indexOf("function hasUnsavedDetailsEditorChanges");const end=s.indexOf("function inspectActiveInlineTitleDraft",start);assert.doesNotMatch(s.slice(start,end),/normaliseDetails\([^,]+, 4000\)|parseUrgentDetailsBody/);});
