"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),source=(file)=>fs.readFileSync(path.join(root,file),"utf8");
function classes(){const names=new Set();return{add(...values){values.forEach((value)=>names.add(value));},remove(...values){values.forEach((value)=>names.delete(value));},toggle(value,present){if(present)names.add(value);else names.delete(value);return !!present;}};}
function runtime(text=""){
  const context={window:{}};vm.createContext(context);vm.runInContext(source("js/pocket-node-content.js"),context);vm.runInContext(source("js/pocket-node-popout-runtime.js"),context);const content=context.window.PocketNodeContent;
  const controls=new Map(),saves=[];let selected=null,start=0,end=0;const document={activeElement:null,body:{classList:classes()},createElement(tag){return element(tag);},getElementById(id){return controls.get(id)||null;},addEventListener(){}};
  function element(tag){const listeners=new Map(),attrs=new Map();const node={tagName:String(tag).toUpperCase(),className:"",style:{},children:[],parentNode:null,textContent:"",value:"",hidden:false,disabled:false,readOnly:false,contentEditable:"false",classList:classes(),addEventListener(type,listener){if(!listeners.has(type))listeners.set(type,[]);listeners.get(type).push(listener);},dispatch(type,values={}){const event={target:node,defaultPrevented:false,preventDefault(){this.defaultPrevented=true;},...values};for(const listener of listeners.get(type)||[])listener(event);return event;},setAttribute(name,value){attrs.set(name,String(value));},getAttribute(name){return attrs.get(name)||null;},appendChild(child){child.parentNode=node;node.children.push(child);return child;},focus(){document.activeElement=node;},select(){},contains(child){return node===child||node.children.some((item)=>item.contains(child));},closest(selector){let current=node;while(current){const names=String(current.className).split(/\s+/);if(selector===".lineText[data-line-id]"&&names.includes("lineText")&&current.getAttribute("data-line-id"))return current;if(selector===".lineGutter[data-line-id]"&&names.includes("lineGutter")&&current.getAttribute("data-line-id"))return current;current=current.parentNode;}return null;},querySelectorAll(selector){const result=[];const visit=(current)=>current.children.forEach((child)=>{if(selector===".lineText[data-line-id]"&&String(child.className).split(/\s+/).includes("lineText")&&child.getAttribute("data-line-id"))result.push(child);visit(child);});visit(node);return result;}};Object.defineProperty(node,"innerHTML",{get(){return"";},set(){node.children=[];}});return node;}
  for(const [id,tag] of Object.entries({titleInput:"input",outlinePane:"div",saveState:"span",saveBtn:"button",saveCloseBtn:"button",unsavedDialog:"div",unsavedSaveBtn:"button",unsavedDiscardBtn:"button",unsavedCancelBtn:"button",closeBtn:"button"}))controls.set(id,element(tag));
  const pane=controls.get("outlinePane");content.parseLines(text).forEach((line,index)=>{const row=element("div"),gutter=element("button"),lineText=element("div");row.className="docRow";row.setAttribute("data-line-id",`line_${index}`);row.setAttribute("data-depth",line.depth);gutter.className="lineGutter";gutter.setAttribute("data-line-id",`line_${index}`);lineText.className="lineText";lineText.setAttribute("data-line-id",`line_${index}`);lineText.textContent=line.content;row.appendChild(gutter);row.appendChild(lineText);pane.appendChild(row);});
  const window={setTimeout(){},addEventListener(){},close(){},opener:{closed:false,PocketNodePopoutWindow:{applyAndSaveFromOwnedPopup(_owner,_popup,payload){saves.push(payload);return{ok:true,applied:true,exported:true,sourceIdentity:{fileSessionId:1,sourceFileName:"fixture.json",sourcePipSession:false,sourceOwnerKind:"json",sourceVaultSessionId:""}};},cancelPendingOpen(){}}}};
  const getSelection=()=>selected?{rangeCount:1,getRangeAt(){return{startContainer:selected,endContainer:selected,startOffset:start,endOffset:end,cloneRange(){const copy={mode:"",offset:0,selectNodeContents(){},setEnd(_node,offset){copy.mode="before";copy.offset=offset;},setStart(_node,offset){copy.mode="after";copy.offset=offset;},toString(){return copy.mode==="before"?selected.textContent.slice(0,copy.offset):selected.textContent.slice(copy.offset);}};return copy;}};}}:{rangeCount:0};
  assert.equal(context.window.PocketNodePopoutRuntime.initialise({id:"fixture",title:"fixture",text,fileSessionId:1,sourceFileName:"fixture.json",sourcePipSession:false,sourceOwnerKind:"json",sourceVaultSessionId:"",originalUpdatedAt:"2026-09-12T00:00:00.000Z",popupOwnerToken:"owner",popupInstanceToken:"popup"},{window,document,content,getSelection,requestAnimationFrame(callback){callback();return 1;}}),true);
  return{pane,saves,rows(){return pane.querySelectorAll(".lineText[data-line-id]");},select(target,from,to){selected=target;start=from;end=to;},paste(target,plain,html="<b>wrong</b>"){return pane.dispatch("paste",{target,clipboardData:{getData(type){return type==="text/plain"?plain:html;}}});},enter(target){return pane.dispatch("keydown",{target,key:"Enter",altKey:false,metaKey:false,ctrlKey:false});},save(){controls.get("saveBtn").dispatch("click");return saves.at(-1);}};
}
const texts=(app)=>app.rows().map((row)=>row.textContent),depths=(app)=>app.rows().map((row)=>Number(row.parentNode.getAttribute("data-depth"))),find=(app,value)=>app.rows().find((row)=>row.textContent===value);
test("P198h real runtime paste canonicalises multiline plain text before Enter",()=>{
  const app=runtime(),target=app.rows()[0];app.select(target,0,0);const event=app.paste(target,"Plain parent\r\n\tchild one\r\n\tchild two\r\n1. numbered one\r\n- bullet one","<div>rich must lose</div>");
  assert.equal(event.defaultPrevented,true);assert.deepEqual(texts(app),["Plain parent","child one","child two","1. numbered one","- bullet one"]);assert.deepEqual(depths(app),[0,1,1,0,0]);assert.equal(app.rows().every((row)=>row.children.length===0),true);assert.equal(app.save().text,"Plain parent\n  child one\n  child two\n1. numbered one\n- bullet one");const gutter=app.rows()[0].parentNode.children[0];assert.match(gutter.className,/branch/);const collapse=app.pane.dispatch("click",{target:gutter});assert.equal(collapse.defaultPrevented,true);assert.deepEqual(texts(app),["Plain parent","1. numbered one","- bullet one"]);app.pane.dispatch("click",{target:gutter});
  app.enter(find(app,"1. numbered one"));assert.deepEqual(texts(app),["Plain parent","child one","child two","1. numbered one","2. ","- bullet one"]);app.enter(find(app,"2. "));assert.equal(texts(app)[4],"");app.enter(find(app,"- bullet one"));assert.equal(texts(app).at(-1),"- ");app.enter(find(app,"- "));assert.equal(texts(app).at(-1),"");
});
test("P198h paste preserves prefix and suffix, inline single lines, relative depth and stale-selection safety",()=>{
  const app=runtime("before after\n      anchor"),target=app.rows()[0];app.select(target,7,7);app.paste(target,"first\n\tchild\nlast");assert.deepEqual(texts(app),["before first","child","lastafter","anchor"]);assert.deepEqual(depths(app),[0,1,0,3]);const first=find(app,"before first");app.select(first,7,12);app.paste(first,"plain","<i>must not win</i>");assert.deepEqual(texts(app),["before plain","child","lastafter","anchor"]);const other=app.rows()[1];app.select(other,0,0);app.paste(app.rows()[0],"wrong\nrow");app.select(null,0,0);app.paste(app.rows()[0],"also\nwrong");assert.deepEqual(texts(app),["before plain","child","lastafter","anchor"]);app.enter(find(app,"lastafter"));assert.deepEqual(texts(app),["before plain","child","lastafter","","anchor"]);
});
